# 1. Carga de datos

## 1.1. Carga de parquet de Saúl

In [25]:
import pandas as pd

# Rutas
path_base = "/home/jarenas/Datasets/PLACE/2025"
file_1 = f"{path_base}/insiders.parquet"
file_2 = f"{path_base}/insiders_unificado.parquet"

# Lectura
df_insiders = pd.read_parquet(file_1, engine="fastparquet")
df_insiders_unificado = pd.read_parquet(file_2, engine="fastparquet")

# Info básica
print("=== insiders.parquet ===")
print(df_insiders.info())
print("\nPrimeras filas:")
display(df_insiders.head())

print("\n=== insiders_unificado.parquet ===")
print(df_insiders_unificado.info())
print("\nPrimeras filas:")
display(df_insiders_unificado.head())

# Tamaños
print("\nTamaños:")
print("insiders:", df_insiders.shape)
print("insiders_unificado:", df_insiders_unificado.shape)

# Columnas
print("\nColumnas insiders:")
print(df_insiders.columns.tolist())

print("\nColumnas insiders_unificado:")
print(df_insiders_unificado.columns.tolist())

=== insiders.parquet ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206869 entries, 0 to 206868
Columns: 210 entries, id to deleted_on
dtypes: datetime64[us, UTC](2), float64(56), int64(6), object(146)
memory usage: 331.4+ MB
None

Primeras filas:

,id,link,summary,title,updated,ContractFolderStatus_ContractFolderID,ContractFolderStatus_ContractFolderStatusCode,ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode,ContractFolderStatus_LocatedContractingParty_ActivityCode,ContractFolderStatus_LocatedContractingParty_BuyerProfileURIID,...,_source_zip,_source_xml,ContractFolderStatus_TenderingTerms_TendererQualificationRequest_OperatingYearsQuantity,ContractFolderStatus_TenderingTerms_TendererQualificationRequest_OperatingYearsDescription,ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name,ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_Description,ContractFolderStatus_TenderResult_SubcontractTerms_Rate,ContractFolderStatus_TenderResult_SubcontractTerms_Description,ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_ID,deleted_on
0,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 905/2021; Órgano de Contratació...,Prestación del servicio de consultoría de prot...,2025-01-31 14:03:32.020000+00:00,905/2021,RES,5,9,https://contrataciondelestado.es/wps/poc?uri=d...,...,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,NaN,None,None,None,NaN,None,NaN,NaT
1,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 755/2021; Órgano de Contratació...,Prestación de los servicios de limpieza diario...,2025-01-31 14:07:45.480000+00:00,755/2021,RES,5,9,https://contrataciondelestado.es/wps/poc?uri=d...,...,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,NaN,None,None,None,NaN,None,NaN,NaT
2,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 0393/2023; Órgano de Contrataci...,Contrato de Suministro de Materiales de oficin...,2025-01-31 14:07:54.109000+00:00,0393/2023,RES,3,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,NaN,None,None,None,NaN,None,NaN,NaT
3,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 85/2025; Órgano de Contratación...,"Servicio de Conserjería, limpieza y mantenimie...",2025-01-31 14:08:46.123000+00:00,85/2025,PUB,3,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,NaN,None,None,None,NaN,None,NaN,NaT
4,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 2024000761 169 C2 ; Órgano de C...,Mantenimiento Custormer First para el sistema ...,2025-01-31 14:09:09.382000+00:00,2024000761 169 C2,RES,8,"[110, 1]",https://contrataciondelestado.es/wps/poc?uri=d...,...,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,NaN,None,None,None,NaN,None,NaN,NaT

=== insiders_unificado.parquet ===
<class 'pandas.core.frame.DataFrame'>
Index: 206869 entries, 0000341715ef5ad5cd96e6635dd8f5f4 to fffff27598b39d72bf9398dba49e9d4e
Columns: 214 entries, id to url.tecnico
dtypes: datetime64[us, UTC](2), float64(56), int64(6), object(150)
memory usage: 339.3+ MB
None

Primeras filas:

,id,link,summary,objective,updated,expedient,ContractFolderStatus_ContractFolderStatusCode,ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode,ContractFolderStatus_LocatedContractingParty_ActivityCode,ContractFolderStatus_LocatedContractingParty_BuyerProfileURIID,...,ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name,ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_Description,ContractFolderStatus_TenderResult_SubcontractTerms_Rate,ContractFolderStatus_TenderResult_SubcontractTerms_Description,ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_ID,deleted_on,url.administrativo,url.id_administrativo,url.id_tecnico,url.tecnico
id_internal,,,,,,,,,,,,,,,,,,,,,
0000341715ef5ad5cd96e6635dd8f5f4,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: DEMA-2025-060; Órgano de Contra...,Servicio de asistencia técnica para apoyar a l...,2025-11-11 06:37:51.614000+00:00,DEMA-2025-060,RES,6,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,None,None,NaN,None,NaN,NaT,https://contrataciondelestado.es/FileSystem/se...,43a456d146ee0ea774fdd13f1d28a754,fe96e35c27318db859a8305bc50102c2,https://contrataciondelestado.es/FileSystem/se...
00004825d6488261a00200033d27b4ad,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 1361/2025; Órgano de Contrataci...,Enajenación de varias parcelas pertenecientes...,2025-07-11 11:40:24.114000+00:00,1361/2025,EV,3,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,None,None,NaN,None,NaN,NaT,https://contrataciondelestado.es/FileSystem/se...,7c0e308e3c61b1eee88604cfb4ee4551,55dd4c74ab31bfefda7bd94319cde6ee,https://contrataciondelestado.es/FileSystem/se...
000091841d3ef1850229951463c03b43,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 223/2025; Órgano de Contratació...,Materiales de PFEA. Aepsa 2024-2025,2025-09-23 08:36:25.107000+00:00,223/2025,RES,3,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,None,None,NaN,None,NaN,NaT,https://contrataciondelestado.es/FileSystem/se...,81224ed3cc813eb7d7d5548d73aea8d2,25c421f025aeb98f49282d4b56438560,https://contrataciondelestado.es/FileSystem/se...
00009612d0786ce151acce9db40116ff,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 22/2025 (GEST 2767/2025); Órgan...,Concesión demanial de setenta (70) plazas de g...,2025-06-27 11:09:40.974000+00:00,22/2025 (GEST 2767/2025),RES,3,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,None,None,NaN,None,NaN,NaT,https://contrataciondelestado.es/FileSystem/se...,6c29ee17ea840131e96ecf29a6420a08,8adddb2ca99d41ecf2da82899a17d8da,https://contrataciondelestado.es/FileSystem/se...
000123efb97ab48f9cf15c112fe31b8e,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: CEA2029/2024; Órgano de Contrat...,Mantenimiento Y Soporte De Una Herramienta Too...,2025-12-17 15:18:55.352000+00:00,CEA2029/2024,ADJ,1,1,https://contrataciondelestado.es/wps/poc?uri=d...,...,None,None,NaN,None,NaN,NaT,None,None,None,None

Tamaños:
insiders: (206869, 210)
insiders_unificado: (206869, 214)

Columnas insiders:
['id', 'link', 'summary', 'title', 'updated', 'ContractFolderStatus_ContractFolderID', 'ContractFolderStatus_ContractFolderStatusCode', 'ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode', 'ContractFolderStatus_LocatedContractingParty_ActivityCode', 'ContractFolderStatus_LocatedContractingParty_BuyerProfileURIID', 'ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_ID_schemeName', 'ContractFolderStatus_LocatedContractingParty_Party_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_CityName', 'ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_PostalZone', 'ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_AddressLine_Line', 'ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_Country_IdentificationCode', 'ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_Country_Name', 'ContractFolderStatus_LocatedContractingParty_Party_Contact_Name', 'ContractFolderStatus_LocatedContractingParty_Party_Contact_Telephone', 'ContractFolderStatus_LocatedContractingParty_Party_Contact_Telefax', 'ContractFolderStatus_LocatedContractingParty_Party_Contact_ElectronicMail', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_ProcurementProject_Name', 'ContractFolderStatus_ProcurementProject_TypeCode', 'ContractFolderStatus_ProcurementProject_SubTypeCode', 'ContractFolderStatus_ProcurementProject_MixContractIndicator', 'ContractFolderStatus_ProcurementProject_BudgetAmount_EstimatedOverallContractAmount', 'ContractFolderStatus_ProcurementProject_BudgetAmount_TotalAmount', 'ContractFolderStatus_ProcurementProject_BudgetAmount_TaxExclusiveAmount', 'ContractFolderStatus_ProcurementProject_RequiredCommodityClassification_ItemClassificationCode', 'ContractFolderStatus_ProcurementProject_RealizedLocation_CountrySubentity', 'ContractFolderStatus_ProcurementProject_RealizedLocation_CountrySubentityCode', 'ContractFolderStatus_ProcurementProject_RealizedLocation_Address_Country_IdentificationCode', 'ContractFolderStatus_ProcurementProject_RealizedLocation_Address_Country_Name', 'ContractFolderStatus_ProcurementProject_PlannedPeriod_DurationMeasure', 'ContractFolderStatus_TenderResult_ResultCode', 'ContractFolderStatus_TenderResult_Description', 'ContractFolderStatus_TenderResult_AwardDate', 'ContractFolderStatus_TenderResult_ReceivedTenderQuantity', 'ContractFolderStatus_TenderResult_LowerTenderAmount', 'ContractFolderStatus_TenderResult_HigherTenderAmount', 'ContractFolderStatus_TenderResult_SMEsReceivedTenderQuantity', 'ContractFolderStatus_TenderResult_SMEAwardedIndicator', 'ContractFolderStatus_TenderResult_Contract_ID', 'ContractFolderStatus_TenderResult_Contract_IssueDate', 'ContractFolderStatus_TenderResult_WinningParty_PartyIdentification_ID', 'ContractFolderStatus_TenderResult_WinningParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_TenderResult_WinningParty_PartyName_Name', 'ContractFolderStatus_TenderResult_WinningParty_PhysicalLocation_Address_CityName', 'ContractFolderStatus_TenderResult_WinningParty_PhysicalLocation_Address_PostalZone', 'ContractFolderStatus_TenderResult_WinningParty_PhysicalLocation_Address_Country_IdentificationCode', 'ContractFolderStatus_TenderResult_AwardedTenderedProject_LegalMonetaryTotal_TaxExclusiveAmount', 'ContractFolderStatus_TenderResult_AwardedTenderedProject_LegalMonetaryTotal_PayableAmount', 'ContractFolderStatus_TenderingTerms_RequiredCurriculaIndicator', 'ContractFolderStatus_TenderingTerms_FundingProgramCode', 'ContractFolderStatus_TenderingTerms_ProcurementNationalLegislationCode', 'ContractFolderStatus_TenderingTerms_ReceivedAppealQuantity', 'ContractFolderStatus_TenderingTerms_RequiredFinancialGuarantee_GuaranteeTypeCode', 'ContractFolderStatus_TenderingTerms_RequiredFinancialGuarantee_AmountRate', 'ContractFolderStatus_TenderingTerms_ProcurementLegislationDocumentReference_ID', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_SpecificTendererRequirement_RequirementTypeCode', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_SpecificTendererRequirement_Description', 'ContractFolderStatus_TenderingTerms_ContractExecutionRequirement_Name', 'ContractFolderStatus_TenderingTerms_ContractExecutionRequirement_ExecutionRequirementCode', 'ContractFolderStatus_TenderingTerms_ContractExecutionRequirement_Description', 'ContractFolderStatus_TenderingTerms_AwardingTerms_AwardingCriteria_AwardingCriteriaTypeCode', 'ContractFolderStatus_TenderingTerms_AwardingTerms_AwardingCriteria_Description', 'ContractFolderStatus_TenderingTerms_AwardingTerms_AwardingCriteria_Note', 'ContractFolderStatus_TenderingTerms_AwardingTerms_AwardingCriteria_AwardingCriteriaSubTypeCode', 'ContractFolderStatus_TenderingTerms_AwardingTerms_AwardingCriteria_WeightNumeric', 'ContractFolderStatus_TenderingTerms_TenderRecipientParty_EndpointID', 'ContractFolderStatus_TenderingTerms_Language_ID', 'ContractFolderStatus_TenderingProcess_ProcedureCode', 'ContractFolderStatus_TenderingProcess_UrgencyCode', 'ContractFolderStatus_TenderingProcess_ContractingSystemCode', 'ContractFolderStatus_TenderingProcess_SubmissionMethodCode', 'ContractFolderStatus_TenderingProcess_OverThresholdIndicator', 'ContractFolderStatus_TenderingProcess_DocumentAvailabilityPeriod_EndDate', 'ContractFolderStatus_TenderingProcess_DocumentAvailabilityPeriod_EndTime', 'ContractFolderStatus_TenderingProcess_TenderSubmissionDeadlinePeriod_EndDate', 'ContractFolderStatus_TenderingProcess_TenderSubmissionDeadlinePeriod_EndTime', 'ContractFolderStatus_TenderingProcess_AuctionTerms_AuctionConstraintIndicator', 'ContractFolderStatus_LegalDocumentReference_ID', 'ContractFolderStatus_LegalDocumentReference_Attachment_ExternalReference_URI', 'ContractFolderStatus_LegalDocumentReference_Attachment_ExternalReference_DocumentHash', 'ContractFolderStatus_TechnicalDocumentReference_ID', 'ContractFolderStatus_TechnicalDocumentReference_Attachment_ExternalReference_URI', 'ContractFolderStatus_TechnicalDocumentReference_Attachment_ExternalReference_DocumentHash', 'ContractFolderStatus_ValidNoticeInfo_NoticeTypeCode', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_PublicationMediaName', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationDocumentReference_IssueDate', 'ContractFolderStatus_GeneralDocument_GeneralDocumentDocumentReference_ID', 'ContractFolderStatus_GeneralDocument_GeneralDocumentDocumentReference_DocumentTypeCode', 'ContractFolderStatus_GeneralDocument_GeneralDocumentDocumentReference_Attachment_ExternalReference_URI', 'ContractFolderStatus_GeneralDocument_GeneralDocumentDocumentReference_Attachment_ExternalReference_FileName', 'ContractFolderStatus_UUID', 'ContractFolderStatus_LocatedContractingParty_Party_WebsiteURI', 'ContractFolderStatus_ProcurementProject_RealizedLocation_Address_CityName', 'ContractFolderStatus_ProcurementProject_RealizedLocation_Address_PostalZone', 'ContractFolderStatus_ProcurementProject_PlannedPeriod_StartDate', 'ContractFolderStatus_ProcurementProjectLot_ID', 'ContractFolderStatus_ProcurementProjectLot_ID_schemeName', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_Name', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_BudgetAmount_TotalAmount', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_BudgetAmount_TaxExclusiveAmount', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RequiredCommodityClassification_ItemClassificationCode', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_CountrySubentity', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_CountrySubentityCode', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_Address_Country_IdentificationCode', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_Address_Country_Name', 'ContractFolderStatus_TenderingTerms_VariantConstraintIndicator', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_EvaluationCriteriaTypeCode', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_Description', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_EvaluationCriteriaTypeCode', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_Description', 'ContractFolderStatus_TenderingProcess_PartPresentationCode', 'ContractFolderStatus_TenderingProcess_MaximumLotPresentationQuantity', 'ContractFolderStatus_TenderingProcess_MaximumTendererAwardedLotsQuantity', 'ContractFolderStatus_AdditionalDocumentReference_ID', 'ContractFolderStatus_AdditionalDocumentReference_Attachment_ExternalReference_URI', 'ContractFolderStatus_AdditionalDocumentReference_Attachment_ExternalReference_DocumentHash', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationRequest_AgencyID', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationRequest_SendDate', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationRequest_SendTime', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_TenderingTerms_PriceRevisionFormulaDescription', 'ContractFolderStatus_ProcurementProject_ContractExtension_OptionValidityPeriod_Description', 'ContractFolderStatus_TenderResult_StartDate', 'ContractFolderStatus_TenderResult_WinningParty_PhysicalLocation_CountrySubentityCode', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationDocumentReference_DocumentTypeCode', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationDocumentReference_Attachment_ExternalReference_URI', 'ContractFolderStatus_ValidNoticeInfo_AdditionalPublicationStatus_AdditionalPublicationDocumentReference_Attachment_ExternalReference_FileName', 'ContractFolderStatus_ContractModification_ID', 'ContractFolderStatus_ContractModification_Note', 'ContractFolderStatus_ContractModification_ContractModificationDurationMeasure', 'ContractFolderStatus_ContractModification_FinalDurationMeasure', 'ContractFolderStatus_ContractModification_ContractID', 'ContractFolderStatus_ContractModification_ContractModificationLegalMonetaryTotal_TaxExclusiveAmount', 'ContractFolderStatus_ContractModification_FinalLegalMonetaryTotal_TaxExclusiveAmount', 'ContractFolderStatus_TenderingTerms_FundingProgram', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_RequiredBusinessClassificationScheme_ID', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_RequiredBusinessClassificationScheme_ClassificationCategory_CodeValue', 'ContractFolderStatus_TenderingProcess_TenderSubmissionDeadlinePeriod_Description', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_ThresholdQuantity', 'ContractFolderStatus_TenderingTerms_AllowedSubcontractTerms_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_AwardingCriteriaTypeCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_AwardingCriteriaSubTypeCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_WeightNumeric', 'ContractFolderStatus_ProcurementProject_PlannedPeriod_EndDate', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_TenderResult_EUNationalsReceivedTenderQuantity', 'ContractFolderStatus_TenderResult_NonEUNationalsReceivedTenderQuantity', 'ContractFolderStatus_TenderResult_AbnormallyLowTendersIndicator', 'ContractFolderStatus_TenderResult_AwardedTenderedProject_ProcurementProjectLotID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_TenderResult_AwardedOwnerNationalityCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_Note', 'ContractFolderStatus_TenderingTerms_RequiredFinancialGuarantee_LiabilityAmount', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_PersonalSituation', 'ContractFolderStatus_ProcurementProject_ContractExtension_OptionsDescription', 'ContractFolderStatus_TenderingProcess_LotsCombinationContractingAuthorityRights', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_EvaluationCriteriaTypeCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_ThresholdQuantity', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_EvaluationCriteriaTypeCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_FinancialEvaluationCriteria_ThresholdQuantity', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_TechnicalEvaluationCriteria_ThresholdQuantity', 'ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_EndDate', 'ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_EndTime', 'ContractFolderStatus_ProcurementProject_RealizedLocation_Address_StreetName', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_Address_CityName', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_TenderingTerms_AllowedSubcontractTerms_Rate', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_SpecificTendererRequirement_RequirementTypeCode', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_TendererQualificationRequest_SpecificTendererRequirement_Description', 'ContractFolderStatus_TenderingProcess_EconomicOperatorShortList_LimitationDescription', 'ContractFolderStatus_TenderingProcess_EconomicOperatorShortList_MaximumQuantity', 'ContractFolderStatus_TenderingProcess_EconomicOperatorShortList_MinimumQuantity', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_Address_PostalZone', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_EmployeeQuantity', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_EmployeeQuantityDescription', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyIdentification_ID_schemeName', 'ContractFolderStatus_TenderingProcess_EconomicOperatorShortList_ExpectedQuantity', 'ContractFolderStatus_TenderResult_WinningParty_PartyLegalEntity_CompanyTypeCode', 'ContractFolderStatus_ProcurementProjectLot_ProcurementProject_RealizedLocation_Address_StreetName', '_source_zip', '_source_xml', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_OperatingYearsQuantity', 'ContractFolderStatus_TenderingTerms_TendererQualificationRequest_OperatingYearsDescription', 'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name', 'ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_Description', 'ContractFolderStatus_TenderResult_SubcontractTerms_Rate', 'ContractFolderStatus_TenderResult_SubcontractTerms_Description', 'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_ID', 'deleted_on']

Columnas insiders_unificado:

## 1.2. Datos crudos - chequeo de número de registros

In [7]:
import zipfile
from pathlib import Path

ZIP_PATH = Path("/home/jarenas/Datasets/PLACE/2025/licitacionesPerfilesContratanteCompleto3_202502.zip")

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    atom_files = [f for f in z.namelist() if f.lower().endswith(".atom")]
    xml_files  = [f for f in z.namelist() if f.lower().endswith(".xml")]

print("Nº .atom:", len(atom_files))
print("Nº .xml :", len(xml_files))
print("\nEjemplos .atom:")
print(atom_files[:10])

Nº .atom: 92
Nº .xml : 0

Ejemplos .atom:
['licitacionesPerfilesContratanteCompleto3.atom', 'licitacionesPerfilesContratanteCompleto3_20250203_180433.atom', 'licitacionesPerfilesContratanteCompleto3_20250203_180433_1.atom', 'licitacionesPerfilesContratanteCompleto3_20250203_180433_2.atom', 'licitacionesPerfilesContratanteCompleto3_20250203_180433_3.atom', 'licitacionesPerfilesContratanteCompleto3_20250203_180433_4.atom', 'licitacionesPerfilesContratanteCompleto3_20250204_181104.atom', 'licitacionesPerfilesContratanteCompleto3_20250204_181104_1.atom', 'licitacionesPerfilesContratanteCompleto3_20250204_181104_2.atom', 'licitacionesPerfilesContratanteCompleto3_20250204_181104_3.atom']

In [8]:
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET

ZIP_PATH = Path("/home/jarenas/Datasets/PLACE/2025/licitacionesPerfilesContratanteCompleto3_202502.zip")
ATOM_NAME = "licitacionesPerfilesContratanteCompleto3_20250203_180433.atom"  # cambia si quieres

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(ATOM_NAME) as f:
        tree = ET.parse(f)
        root = tree.getroot()

print("Root:", root.tag)
entries = [e for e in root if localname(e.tag) == "entry"]
print("N entries:", len(entries))
print("First entry tag:", entries[0].tag if entries else None)

Root: {http://www.w3.org/2005/Atom}feed
N entries: 499
First entry tag: {http://www.w3.org/2005/Atom}entry

In [9]:
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET

ZIP_PATH = Path("/home/jarenas/Datasets/PLACE/2025/licitacionesPerfilesContratanteCompleto3_202502.zip")
ATOM_NAME = "licitacionesPerfilesContratanteCompleto3_20250203_180433.atom"  # el que abriste

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def child_text(entry, name):
    for c in list(entry):
        if localname(c.tag) == name:
            return (c.text or "").strip()
    return None

def first_link_href(entry):
    for c in list(entry):
        if localname(c.tag) == "link":
            # suele venir en attrib['href']
            return c.attrib.get("href")
    return None

def get_content_elem(entry):
    for c in list(entry):
        if localname(c.tag) == "content":
            return c
    return None

def extract_payload_root(content_elem):
    if content_elem is None:
        return None
    children = list(content_elem)
    if children:
        return children[0]  # normalmente aquí viene el XML grande
    txt = (content_elem.text or "").strip()
    if txt.startswith("<"):
        try:
            return ET.fromstring(txt)
        except ET.ParseError:
            return None
    return None

with zipfile.ZipFile(ZIP_PATH, "r") as z:
    with z.open(ATOM_NAME) as f:
        tree = ET.parse(f)
        root = tree.getroot()

entries = [e for e in list(root) if localname(e.tag) == "entry"]
print("N entries:", len(entries))

for i, e in enumerate(entries[:3]):
    print(f"\n=== ENTRY {i} ===")
    print("id:", child_text(e, "id"))
    print("updated:", child_text(e, "updated"))
    print("title:", child_text(e, "title"))
    s = child_text(e, "summary")
    print("summary head:", (s[:200] + "...") if s and len(s) > 200 else s)
    print("link:", first_link_href(e))

    content = get_content_elem(e)
    print("content attrib:", content.attrib if content is not None else None)

    payload = extract_payload_root(content)
    print("payload tag:", payload.tag if payload is not None else None)
    if payload is not None:
        print("payload children tags (first 10):")
        for c in list(payload)[:10]:
            print(" -", c.tag)

N entries: 499

=== ENTRY 0 ===
id: https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16344055
updated: 2025-02-03T15:43:08.414+01:00
title: Construcción, montaje y desmontaje de carpas, stands modulares y otros equipamientos complementarios para la XX Feria Internacional de Turismo Ornitológico, FIO 2025.
summary head: Id licitación: PO04624; Órgano de Contratación: Administrador Unico de FEVAL Gestión de Sevicios S.L.U.; Importe: 220950 EUR; Estado: EV
link: https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvl=kfaj%2B1FG%2FMCOUi78BmzhOQ%3D%3D
content attrib: None
payload tag: None

=== ENTRY 1 ===
id: https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/15907149
updated: 2025-02-03T15:42:27.700+01:00
title: Servicio de prevención de riesgos laborales y medicina del trabajo del Ayuntamiento de Cambre
summary head: Id licitación: 2024/C004/000020; Órgano de Contratación: Junta de Gobierno Local del Ayuntamiento de Cambre; Importe: 17406.42 EUR; Estado: EV
link: https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvl=TljohESzq0YQyBAnWzHfCg%3D%3D
content attrib: None
payload tag: None

=== ENTRY 2 ===
id: https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/9467796
updated: 2025-02-03T15:41:29.410+01:00
title: Servicios de asesoramiento, mediación, asistencia técnica y redacción de pliegos de prescripciones técnicas en materia de seguros
summary head: Id licitación: PL013/2022; Órgano de Contratación: Consejo de Administración de Limpieza de Málaga Sociedad Anónima Municipal; Importe: 0 EUR; Estado: RES
link: https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&idEvl=s36CRZLjCqoSugstABGr5A%3D%3D
content attrib: None
payload tag: None

In [12]:
for e in entries:
    payload = extract_payload_root(get_content_elem(e))
    if payload is not None:
        payload_str = ET.tostring(payload, encoding="unicode")
        print(payload_str)  # copia y pégame esto
        break
else:
    # si no hay payload dentro de content, imprimimos el entry para ver dónde viene
    e0 = entries[0]
    entry_str = ET.tostring(e0, encoding="unicode")
    print(entry_str)

<ns0:entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:ns1="urn:dgpe:names:draft:codice-place-ext:schema:xsd:CommonAggregateComponents-2" xmlns:ns2="urn:dgpe:names:draft:codice:schema:xsd:CommonBasicComponents-2" xmlns:ns3="urn:dgpe:names:draft:codice-place-ext:schema:xsd:CommonBasicComponents-2" xmlns:ns4="urn:dgpe:names:draft:codice:schema:xsd:CommonAggregateComponents-2">
        <ns0:id>https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16344055</ns0:id>
        <ns0:link href="https://contrataciondelestado.es/wps/poc?uri=deeplink:detalle_licitacion&amp;idEvl=kfaj%2B1FG%2FMCOUi78BmzhOQ%3D%3D" />
        <ns0:summary type="text">Id licitación: PO04624; Órgano de Contratación: Administrador Unico de FEVAL Gestión de Sevicios S.L.U.; Importe: 220950 EUR; Estado: EV</ns0:summary>
        <ns0:title>Construcción, montaje y desmontaje de carpas, stands modulares y otros equipamientos complementarios para la XX Feria Internacional de Turismo Ornitológico, FIO 2025.</ns0:title>
        <ns0:updated>2025-02-03T15:43:08.414+01:00</ns0:updated>
        <ns1:ContractFolderStatus>
            <ns2:ContractFolderID>PO04624</ns2:ContractFolderID>
            <ns3:ContractFolderStatusCode listURI="https://contrataciondelestado.es/codice/cl/2.04/SyndicationContractFolderStatusCode-2.04.gc" languageID="es">EV</ns3:ContractFolderStatusCode>
            <ns1:LocatedContractingParty>
                <ns2:ContractingPartyTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.10/ContractingAuthorityCode-2.10.gc">7</ns2:ContractingPartyTypeCode>
                <ns2:ActivityCode listURI="http://contrataciondelestado.es/codice/cl/2.10/ContractingAuthorityActivityCode-2.10.gc">1</ns2:ActivityCode>
                <ns2:BuyerProfileURIID>https://contrataciondelestado.es/wps/poc?uri=deeplink:perfilContratante&amp;idBp=FGfriDaLlBsQK2TEfXGy%2BA%3D%3D</ns2:BuyerProfileURIID>
                <ns4:Party>
                    <ns2:WebsiteURI>http://www.feval.com</ns2:WebsiteURI>
                    <ns4:PartyIdentification>
                        <ns2:ID schemeName="NIF">B06574271</ns2:ID>
                    </ns4:PartyIdentification>
                    <ns4:PartyIdentification>
                        <ns2:ID schemeName="ID_PLATAFORMA">51054610149221</ns2:ID>
                    </ns4:PartyIdentification>
                    <ns4:PartyName>
                        <ns2:Name>Administrador Unico de FEVAL Gestión de Sevicios S.L.U.</ns2:Name>
                    </ns4:PartyName>
                    <ns4:PostalAddress>
                        <ns2:CityName>Don Benito</ns2:CityName>
                        <ns2:PostalZone>06400</ns2:PostalZone>
                        <ns4:AddressLine>
                            <ns2:Line>Avda. de Feval s/n</ns2:Line>
                        </ns4:AddressLine>
                        <ns4:Country>
                            <ns2:IdentificationCode listURI="http://contrataciondelestado.es/codice/cl/2.08/CountryIdentificationCode-2.08.gc">ES</ns2:IdentificationCode>
                            <ns2:Name>España</ns2:Name>
                        </ns4:Country>
                    </ns4:PostalAddress>
                    <ns4:Contact>
                        <ns2:Name>Administrador Unico de FEVAL Gestión de Sevicios S.L.U.</ns2:Name>
                        <ns2:Telephone>924829100</ns2:Telephone>
                        <ns2:Telefax>924810752</ns2:Telefax>
                        <ns2:ElectronicMail>irollano@feval.com</ns2:ElectronicMail>
                    </ns4:Contact>
                </ns4:Party>
                <ns1:ParentLocatedParty>
                    <ns4:PartyName>
                        <ns2:Name>Extremadura</ns2:Name>
                    </ns4:PartyName>
                    <ns1:ParentLocatedParty>
                        <ns4:PartyName>
                            <ns2:Name>SOCIEDADES, FUNDACIONES Y CONSORCIOS COMUNIDADES AUTÓNOMAS</ns2:Name>
                        </ns4:PartyName>
                        <ns1:ParentLocatedParty>
                            <ns4:PartyName>
<ns2:Name>OTRAS ENTIDADES DEL SECTOR PÚBLICO</ns2:Name>
                            </ns4:PartyName>
                            <ns1:ParentLocatedParty>
<ns4:PartyName>
    <ns2:Name>Sector Público</ns2:Name>
</ns4:PartyName>
                            </ns1:ParentLocatedParty>
                        </ns1:ParentLocatedParty>
                    </ns1:ParentLocatedParty>
                </ns1:ParentLocatedParty>
            </ns1:LocatedContractingParty>
            <ns4:ProcurementProject>
                <ns2:Name>Construcción, montaje y desmontaje de carpas, stands modulares y otros equipamientos complementarios para la XX Feria Internacional de Turismo Ornitológico, FIO 2025.</ns2:Name>
                <ns2:TypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/ContractCode-2.08.gc">2</ns2:TypeCode>
                <ns2:SubTypeCode listURI="http://contrataciondelestado.es/codice/cl/1.04/ServiceContractCode-1.04.gc">27</ns2:SubTypeCode>
                <ns2:MixContractIndicator>false</ns2:MixContractIndicator>
                <ns4:BudgetAmount>
                    <ns2:EstimatedOverallContractAmount currencyID="EUR">220950</ns2:EstimatedOverallContractAmount>
                    <ns2:TotalAmount currencyID="EUR">267349.5</ns2:TotalAmount>
                    <ns2:TaxExclusiveAmount currencyID="EUR">220950</ns2:TaxExclusiveAmount>
                </ns4:BudgetAmount>
                <ns4:RequiredCommodityClassification>
                    <ns2:ItemClassificationCode listURI="http://contrataciondelestado.es/codice/cl/2.04/CPV2008-2.04.gc">79956000</ns2:ItemClassificationCode>
                </ns4:RequiredCommodityClassification>
                <ns4:RealizedLocation>
                    <ns2:CountrySubentity>Badajoz</ns2:CountrySubentity>
                    <ns2:CountrySubentityCode listURI="http://contrataciondelestado.es/codice/cl/2.08/NUTS-2021.gc">ES431</ns2:CountrySubentityCode>
                    <ns4:Address>
                        <ns2:CityName>VILLAREAL DE SAN CARLOS </ns2:CityName>
                        <ns2:PostalZone>10695</ns2:PostalZone>
                        <ns4:Country>
                            <ns2:IdentificationCode listURI="http://contrataciondelestado.es/codice/cl/2.08/CountryIdentificationCode-2.08.gc">ES</ns2:IdentificationCode>
                            <ns2:Name>España</ns2:Name>
                        </ns4:Country>
                    </ns4:Address>
                </ns4:RealizedLocation>
                <ns4:PlannedPeriod>
                    <ns2:DurationMeasure unitCode="MON">3</ns2:DurationMeasure>
                </ns4:PlannedPeriod>
            </ns4:ProcurementProject>
            <ns4:TenderingTerms>
                <ns2:RequiredCurriculaIndicator>false</ns2:RequiredCurriculaIndicator>
                <ns2:VariantConstraintIndicator>false</ns2:VariantConstraintIndicator>
                <ns2:PriceRevisionFormulaDescription>no procede </ns2:PriceRevisionFormulaDescription>
                <ns2:FundingProgramCode listURI="http://contrataciondelestado.es/codice/cl/2.08/FundingProgramCode-2.08.gc" name="Financiación con fondos de la UE">EU</ns2:FundingProgramCode>
                <ns2:FundingProgramCode listURI="http://contrataciondelestado.es/codice/cl/2.08/FundingProgramCode-2.08.gc" name="Fondo Europeo de Desarrollo Regional">FEDER</ns2:FundingProgramCode>
                <ns2:FundingProgram>POSICIONAMIENTO DEL DESTINO EXTREMADURA EN FERIAS NACIONALES</ns2:FundingProgram>
                <ns2:ProcurementNationalLegislationCode listURI="https://contrataciondelestado.es/codice/cl/2.08/ProcurementNationalLegislationCode-2.08.gc">3</ns2:ProcurementNationalLegislationCode>
                <ns4:RequiredFinancialGuarantee>
                    <ns2:GuaranteeTypeCode listURI="http://contrataciondelestado.es/codice/cl/1.04/GuaranteeTypeCode-1.04.gc">2</ns2:GuaranteeTypeCode>
                    <ns2:AmountRate>5</ns2:AmountRate>
                </ns4:RequiredFinancialGuarantee>
                <ns4:ProcurementLegislationDocumentReference>
                    <ns2:ID>N/A</ns2:ID>
                </ns4:ProcurementLegislationDocumentReference>
                <ns4:TendererQualificationRequest>
                    <ns4:TechnicalEvaluationCriteria>
                        <ns2:EvaluationCriteriaTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.0/TechnicalCapabilityTypeCode-2.0.gc">ZZZ</ns2:EvaluationCriteriaTypeCode>
                        <ns2:Description>Según CRC SOLVENCIA TECNICA</ns2:Description>
                    </ns4:TechnicalEvaluationCriteria>
                    <ns4:SpecificTendererRequirement>
                        <ns2:RequirementTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/DeclarationTypeCode-2.08.gc">2</ns2:RequirementTypeCode>
                        <ns2:Description>No prohibición para contratar</ns2:Description>
                    </ns4:SpecificTendererRequirement>
                    <ns4:SpecificTendererRequirement>
                        <ns2:RequirementTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/DeclarationTypeCode-2.08.gc">1</ns2:RequirementTypeCode>
                        <ns2:Description>Capacidad de obrar</ns2:Description>
                    </ns4:SpecificTendererRequirement>
                    <ns4:SpecificTendererRequirement>
                        <ns2:RequirementTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/DeclarationTypeCode-2.08.gc">8</ns2:RequirementTypeCode>
                        <ns2:Description>Estar prerregistrado en el ROLECE, y declarar que no ha habido modificaciones en los datos registrados</ns2:Description>
                    </ns4:SpecificTendererRequirement>
                </ns4:TendererQualificationRequest>
                <ns4:AwardingTerms>
                    <ns4:AwardingCriteria>
                        <ns2:AwardingCriteriaTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.0/AwardingCriteriaCode-2.0.gc">OBJ</ns2:AwardingCriteriaTypeCode>
                        <ns2:Description>Cambio de carpas definidas a dos aguas por cubiertas poligonales</ns2:Description>
                        <ns2:Note>Cambio de carpas definidas a dos aguas por cubiertas poligonales</ns2:Note>
                        <ns2:AwardingCriteriaSubTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.09/AwardingCriteriaAutomaticallyEvaluatedSubTypeCode-2.09.gc">2</ns2:AwardingCriteriaSubTypeCode>
                        <ns2:WeightNumeric>25</ns2:WeightNumeric>
                    </ns4:AwardingCriteria>
                    <ns4:AwardingCriteria>
                        <ns2:AwardingCriteriaTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.0/AwardingCriteriaCode-2.0.gc">OBJ</ns2:AwardingCriteriaTypeCode>
                        <ns2:Description>Precio </ns2:Description>
                        <ns2:Note>50 puntos precio según fórmula establecida en CRC ( PCAP)</ns2:Note>
                        <ns2:AwardingCriteriaSubTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.09/AwardingCriteriaAutomaticallyEvaluatedSubTypeCode-2.09.gc">1</ns2:AwardingCriteriaSubTypeCode>
                        <ns2:WeightNumeric>50</ns2:WeightNumeric>
                    </ns4:AwardingCriteria>
                    <ns4:AwardingCriteria>
                        <ns2:AwardingCriteriaTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.0/AwardingCriteriaCode-2.0.gc">OBJ</ns2:AwardingCriteriaTypeCode>
                        <ns2:Description>Mejora técnica de instalación y nivelado de suelo mediante tarima tipo Layher.</ns2:Description>
                        <ns2:Note>Mejora técnica de instalación y nivelado de suelo mediante tarima tipo Layher.</ns2:Note>
                        <ns2:AwardingCriteriaSubTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.09/AwardingCriteriaAutomaticallyEvaluatedSubTypeCode-2.09.gc">2</ns2:AwardingCriteriaSubTypeCode>
                        <ns2:WeightNumeric>25</ns2:WeightNumeric>
                    </ns4:AwardingCriteria>
                </ns4:AwardingTerms>
                <ns4:TenderRecipientParty>
                    <ns2:EndpointID>https://contrataciondelestado.es</ns2:EndpointID>
                </ns4:TenderRecipientParty>
                <ns4:Language>
                    <ns2:ID>es</ns2:ID>
                </ns4:Language>
            </ns4:TenderingTerms>
            <ns4:TenderingProcess>
                <ns2:ProcedureCode listURI="https://contrataciondelestado.es/codice/cl/2.07/SyndicationTenderingProcessCode-2.07.gc">1</ns2:ProcedureCode>
                <ns2:UrgencyCode listURI="http://contrataciondelestado.es/codice/cl/1.04/DiligenceTypeCode-1.04.gc">1</ns2:UrgencyCode>
                <ns2:ContractingSystemCode listURI="http://contrataciondelestado.es/codice/cl/2.08/ContractingSystemTypeCode-2.08.gc">0</ns2:ContractingSystemCode>
                <ns2:SubmissionMethodCode listURI="http://contrataciondelestado.es/codice/cl/1.04/TenderDeliveryCode-1.04.gc">1</ns2:SubmissionMethodCode>
                <ns2:OverThresholdIndicator>false</ns2:OverThresholdIndicator>
                <ns4:DocumentAvailabilityPeriod>
                    <ns2:EndDate>2025-01-08</ns2:EndDate>
                    <ns2:EndTime>23:59:00</ns2:EndTime>
                </ns4:DocumentAvailabilityPeriod>
                <ns4:TenderSubmissionDeadlinePeriod>
                    <ns2:EndDate>2025-01-08</ns2:EndDate>
                    <ns2:EndTime>23:59:00</ns2:EndTime>
                    <ns2:Description>20 DÍAS NATURALES PARA PRESENTACIÓN DE OFERTAS </ns2:Description>
                </ns4:TenderSubmissionDeadlinePeriod>
            </ns4:TenderingProcess>
            <ns4:LegalDocumentReference>
                <ns2:ID>pcap_servicios_abierto_po04624_signed.pdf</ns2:ID>
                <ns4:Attachment>
                    <ns4:ExternalReference>
                        <ns2:URI>https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=ATe8lY/LNLodaIUeicnsArnpcZ%2BI3/3XBmdU5vs1peCRp6x/5CRI2%2BQKl5%2BIZbwegH77xu3LYQR8maSF54exMlgYmwKc973a0fhxCZIzoauCx2e6p7hqtlp2aFupgHMr&amp;cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D</ns2:URI>
                        <ns2:DocumentHash>GAqWw0xNNQsl9HoeeJkE4zseV+I=</ns2:DocumentHash>
                    </ns4:ExternalReference>
                </ns4:Attachment>
            </ns4:LegalDocumentReference>
            <ns4:TechnicalDocumentReference>
                <ns2:ID>pliegos_t_cnicos_montaje_carpas_fio_2025_anexos_signed.pdf</ns2:ID>
                <ns4:Attachment>
                    <ns4:ExternalReference>
                        <ns2:URI>https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=oxSo29ZBWAmYLoezTPIMW1feCX7ATCVo63BJ3IlWajt7A6m9eFBULBcDMxmekfRAo2BKpGJ%2BMnYq1jyTS19rVm2WY0z4iotRfjVgbEBBviV7QB3HKyQaFUExmUVQCerk&amp;cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D</ns2:URI>
                        <ns2:DocumentHash>3N+nqG4l2ZvJrPewhFRpyQ/AvFU=</ns2:DocumentHash>
                    </ns4:ExternalReference>
                </ns4:Attachment>
            </ns4:TechnicalDocumentReference>
            <ns4:AdditionalDocumentReference>
                <ns2:ID>anexo_i_crc_servicios_abierto_po04624_signed.pdf</ns2:ID>
                <ns4:Attachment>
                    <ns4:ExternalReference>
                        <ns2:URI>https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=n%2B6eLA%2BZqtaEKi/7KZYZ6cpHCg9qh8PBpm65qigOtJWAhQjh0cXZVrhSubBo8co4wIt9CHW7IXGFeA98%2BgkLYOu2ibAuoEficMNVtQEt94p45ClyWkoJ44mKM70IFcOu&amp;cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D</ns2:URI>
                        <ns2:DocumentHash>gQAOLKSYIicxpWqSTVBWpCyxt6U=</ns2:DocumentHash>
                    </ns4:ExternalReference>
                </ns4:Attachment>
            </ns4:AdditionalDocumentReference>
            <ns4:AdditionalDocumentReference>
                <ns2:ID>ANEXOS II A IX - SERVICIOS ABIERTO - PO04624.doc</ns2:ID>
                <ns4:Attachment>
                    <ns4:ExternalReference>
                        <ns2:URI>https://contrataciondelestado.es/FileSystem/servlet/GetDocumentByIdServlet?DocumentIdParam=FhLFSzLR4iQRtjUeHMDxt1wO2N%2BMAfJh8jOv5yZSGjI6H/SGIDDyyNIiIzfNrY5iObBURJ%2BQ1SAx4SpQ2yWfCC2ifRZUE%2BKAW6GBkGqi8UJ7QB3HKyQaFUExmUVQCerk&amp;cifrado=QUC1GjXXSiLkydRHJBmbpw%3D%3D</ns2:URI>
                        <ns2:DocumentHash>Oh1CpNlfmTVo2tkj3QhZhE8jAEA=</ns2:DocumentHash>
                    </ns4:ExternalReference>
                </ns4:Attachment>
            </ns4:AdditionalDocumentReference>
            <ns1:ValidNoticeInfo>
                <ns3:NoticeTypeCode listURI="https://contrataciondelestado.es/codice/cl/2.11/TenderingNoticeTypeCode-2.11.gc">DOC_CD</ns3:NoticeTypeCode>
                <ns1:AdditionalPublicationStatus>
                    <ns3:PublicationMediaName>Perfil del contratante</ns3:PublicationMediaName>
                    <ns1:AdditionalPublicationDocumentReference>
                        <ns2:IssueDate>2024-12-19</ns2:IssueDate>
                    </ns1:AdditionalPublicationDocumentReference>
                    <ns1:AdditionalPublicationDocumentReference>
                        <ns2:IssueDate>2025-01-02</ns2:IssueDate>
                    </ns1:AdditionalPublicationDocumentReference>
                    <ns1:AdditionalPublicationDocumentReference>
                        <ns2:IssueDate>2025-01-07</ns2:IssueDate>
                    </ns1:AdditionalPublicationDocumentReference>
                </ns1:AdditionalPublicationStatus>
            </ns1:ValidNoticeInfo>
            <ns1:ValidNoticeInfo>
                <ns3:NoticeTypeCode listURI="https://contrataciondelestado.es/codice/cl/2.11/TenderingNoticeTypeCode-2.11.gc">DOC_CN</ns3:NoticeTypeCode>
                <ns1:AdditionalPublicationStatus>
                    <ns3:PublicationMediaName>Perfil del contratante</ns3:PublicationMediaName>
                    <ns1:AdditionalPublicationDocumentReference>
                        <ns2:IssueDate>2024-12-19</ns2:IssueDate>
                    </ns1:AdditionalPublicationDocumentReference>
                </ns1:AdditionalPublicationStatus>
            </ns1:ValidNoticeInfo>
            <ns1:GeneralDocument>
                <ns1:GeneralDocumentDocumentReference>
                    <ns2:ID>2025-75484bb2-6034-4c9e-824f-9996812dddb6</ns2:ID>
                    <ns2:DocumentTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/GeneralContractDocuments-2.08.gc">1</ns2:DocumentTypeCode>
                    <ns4:Attachment>
                        <ns4:ExternalReference>
                            <ns2:URI>https://contrataciondelestado.es/wps/wcm/connect/PLACE_es/Site/area/docAccCmpnt?srv=cmpnt&amp;cmpntname=GetDocumentsById&amp;source=library&amp;DocumentIdParam=2025-75484bb2-6034-4c9e-824f-9996812dddb6</ns2:URI>
                            <ns2:FileName>Actos públicos informativos o de aperturas de ofertas</ns2:FileName>
                        </ns4:ExternalReference>
                    </ns4:Attachment>
                </ns1:GeneralDocumentDocumentReference>
            </ns1:GeneralDocument>
            <ns1:GeneralDocument>
                <ns1:GeneralDocumentDocumentReference>
                    <ns2:ID>2025-81b2a74c-766d-4e91-82f1-144058470182</ns2:ID>
                    <ns2:DocumentTypeCode listURI="http://contrataciondelestado.es/codice/cl/2.08/GeneralContractDocuments-2.08.gc">ZZZ</ns2:DocumentTypeCode>
                    <ns4:Attachment>
                        <ns4:ExternalReference>
                            <ns2:URI>https://contrataciondelestado.es/wps/wcm/connect/PLACE_es/Site/area/docAccCmpnt?srv=cmpnt&amp;cmpntname=GetDocumentsById&amp;source=library&amp;DocumentIdParam=2025-81b2a74c-766d-4e91-82f1-144058470182</ns2:URI>

In [13]:
import zipfile
from pathlib import Path
import xml.etree.ElementTree as ET
import pandas as pd

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def flatten_xml(elem, prefix="", out=None, join="_"):
    """
    Aplana un árbol XML a un dict.
    - Usa localname(tag) para ignorar namespaces.
    - Incluye atributos como <tag>@attr
    - Si hay repetidos, los indexa: Field, Field_1, Field_2...
    """
    if out is None:
        out = {}

    tag = localname(elem.tag)
    base = f"{prefix}{join}{tag}" if prefix else tag

    # atributos
    for k, v in elem.attrib.items():
        out[f"{base}{join}@{k}"] = v

    children = list(elem)
    text = (elem.text or "").strip()

    if not children:
        # hoja
        if text != "":
            key = base
            if key in out:
                # colisión: indexamos
                i = 1
                while f"{key}{join}{i}" in out:
                    i += 1
                out[f"{key}{join}{i}"] = text
            else:
                out[key] = text
        return out

    # nodo con hijos: si tiene texto "real" también lo guardamos
    if text != "":
        out[f"{base}{join}#text"] = text

    # procesar hijos; si hay repetidos, indexar
    counts = {}
    for ch in children:
        ch_tag = localname(ch.tag)
        counts[ch_tag] = counts.get(ch_tag, 0) + 1

    seen = {}
    for ch in children:
        ch_tag = localname(ch.tag)
        seen[ch_tag] = seen.get(ch_tag, 0) + 1
        # si está repetido, sufijo _{idx}
        ch_prefix = base
        if counts[ch_tag] > 1:
            ch_prefix = f"{base}{join}{ch_tag}{join}{seen[ch_tag]}"
            # y seguimos aplanando bajo ese prefijo "indexado"
            flatten_xml(ch, prefix=ch_prefix, out=out, join=join)
        else:
            flatten_xml(ch, prefix=base, out=out, join=join)

    return out

def parse_atom_from_zip(zip_path: Path, atom_name: str):
    """
    Devuelve lista de dicts (1 dict por entry).
    Incluye campos Atom + flatten de ContractFolderStatus.
    """
    records = []
    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(atom_name) as f:
            tree = ET.parse(f)
            root = tree.getroot()

    for entry in root:
        if localname(entry.tag) != "entry":
            continue

        rec = {
            "id": None,
            "link": None,
            "summary": None,
            "title": None,
            "updated": None,
            "_source_zip": zip_path.name,
            "_source_atom": atom_name,
        }

        # hijos directos del entry
        for ch in list(entry):
            ln = localname(ch.tag)

            if ln == "id":
                rec["id"] = (ch.text or "").strip()

            elif ln == "updated":
                rec["updated"] = (ch.text or "").strip()

            elif ln == "title":
                rec["title"] = (ch.text or "").strip()

            elif ln == "summary":
                rec["summary"] = (ch.text or "").strip()

            elif ln == "link":
                rec["link"] = ch.attrib.get("href")

            elif ln == "ContractFolderStatus":
                flat = flatten_xml(ch, prefix="ContractFolderStatus")
                rec.update(flat)

        records.append(rec)

    return records

In [14]:
BASE = Path("/home/jarenas/Datasets/PLACE/2025")
ZIP_PATH = BASE / "licitacionesPerfilesContratanteCompleto3_202502.zip"
ATOM_NAME = "licitacionesPerfilesContratanteCompleto3_20250203_180433.atom"

recs = parse_atom_from_zip(ZIP_PATH, ATOM_NAME)
df_one = pd.DataFrame(recs)

print(df_one.shape)
print(df_one.columns[:30])
print(df_one[["id","updated","title"]].head(3))

(499, 5313)
Index(['id', 'link', 'summary', 'title', 'updated', '_source_zip',
       '_source_atom',
       'ContractFolderStatus_ContractFolderStatus_ContractFolderID',
       'ContractFolderStatus_ContractFolderStatus_ContractFolderStatusCode_@listURI',
       'ContractFolderStatus_ContractFolderStatus_ContractFolderStatusCode_@languageID',
       'ContractFolderStatus_ContractFolderStatus_ContractFolderStatusCode',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode_@listURI',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_ActivityCode_@listURI',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_ActivityCode',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_BuyerProfileURIID',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_WebsiteURI',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_1_PartyIdentification_ID_@schemeName',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_1_PartyIdentification_ID',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_2_PartyIdentification_ID_@schemeName',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PartyIdentification_2_PartyIdentification_ID',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PartyName_Name',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_CityName',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_PostalZone',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_AddressLine_Line',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_Country_IdentificationCode_@listURI',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_Country_IdentificationCode',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_PostalAddress_Country_Name',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_Contact_Name',
       'ContractFolderStatus_ContractFolderStatus_LocatedContractingParty_Party_Contact_Telephone'],
      dtype='object')
                                                  id  \
0  https://contrataciondelestado.es/sindicacion/l...
1  https://contrataciondelestado.es/sindicacion/l...
2  https://contrataciondelestado.es/sindicacion/l...

                         updated  \
0  2025-02-03T15:43:08.414+01:00
1  2025-02-03T15:42:27.700+01:00
2  2025-02-03T15:41:29.410+01:00

                                               title
0  Construcción, montaje y desmontaje de carpas, ...
1  Servicio de prevención de riesgos laborales y ...
2  Servicios de asesoramiento, mediación, asisten...

In [17]:
from pathlib import Path
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
import os

BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_paths = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def list_atom_files_in_zip(zip_path: Path):
    with zipfile.ZipFile(zip_path, "r") as z:
        return [n for n in z.namelist() if n.lower().endswith(".atom")]

def process_one_atom(task):
    """
    task: (zip_path_str, atom_name, collect_ids)
    returns: (zip_name, atom_name, n_entries, ids_list_or_None)
    """
    zip_path_str, atom_name, collect_ids = task
    zip_path = Path(zip_path_str)

    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(atom_name) as f:
            root = ET.parse(f).getroot()

    n_entries = 0
    ids = [] if collect_ids else None

    for entry in list(root):
        if localname(entry.tag) != "entry":
            continue
        n_entries += 1
        if collect_ids:
            for ch in list(entry):
                if localname(ch.tag) == "id":
                    ids.append((ch.text or "").strip())
                    break

    return zip_path.name, atom_name, n_entries, ids

# -------- CONFIG --------
COLLECT_IDS = False                 # True si quieres sets de ids
MAX_WORKERS = min(20, os.cpu_count() or 1)
PROGRESS_EVERY = 25                 # imprime cada 25 atoms completados
# ------------------------

# Build tasks
tasks = []
zip_to_atoms = {}
for zp in zip_paths:
    atoms = list_atom_files_in_zip(zp)
    zip_to_atoms[zp.name] = len(atoms)
    for a in atoms:
        tasks.append((str(zp), a, COLLECT_IDS))

print("ZIPs:", len(zip_paths))
print("Total atom files:", len(tasks))
print("Workers:", MAX_WORKERS)

t0 = time.time()

# Aggregators
zip_entries = {zp.name: 0 for zp in zip_paths}
zip_atoms_done = {zp.name: 0 for zp in zip_paths}
total_entries = 0

all_ids = [] if COLLECT_IDS else None

done = 0
with ProcessPoolExecutor(max_workers=MAX_WORKERS) as ex:
    futures = [ex.submit(process_one_atom, t) for t in tasks]

    for fut in as_completed(futures):
        zip_name, atom_name, n_entries, ids = fut.result()

        done += 1
        total_entries += n_entries
        zip_entries[zip_name] += n_entries
        zip_atoms_done[zip_name] += 1

        if COLLECT_IDS and ids:
            all_ids.extend(ids)

        if done % PROGRESS_EVERY == 0 or done == len(tasks):
            elapsed = time.time() - t0
            # muestra también el ZIP "más avanzado" por completitud
            # (opcional: puedes comentar esto si molesta)
            z_sample = max(zip_atoms_done, key=lambda k: zip_atoms_done[k])
            print(
                f"[{done}/{len(tasks)} atoms] total_entries={total_entries:,} "
                f"| elapsed={elapsed:,.1f}s | sample_zip={z_sample} "
                f"({zip_atoms_done[z_sample]}/{zip_to_atoms[z_sample]} atoms)"
            )

elapsed = time.time() - t0
print("\nDONE. Total entries:", total_entries, "| elapsed:", f"{elapsed:.1f}s")

# Summary per ZIP
df_zip_counts = pd.DataFrame(
    [(z, zip_to_atoms[z], zip_entries[z], zip_atoms_done[z]) for z in zip_entries.keys()],
    columns=["zip", "n_atom_files", "n_entries", "atoms_done"]
).sort_values("zip")

print("\n=== RESUMEN POR ZIP ===")
print(df_zip_counts)

# Compare with parquet counts
df_insiders = pd.read_parquet(BASE / "insiders.parquet", engine="fastparquet")
df_unif_old = pd.read_parquet(BASE / "insiders_unificado.parquet", engine="fastparquet")

print("\nParquet rows:")
print("insiders:", df_insiders.shape[0], "unique ids:", df_insiders["id"].nunique())
print("unif_old:", df_unif_old.shape[0], "unique ids:", df_unif_old["id"].nunique())

if COLLECT_IDS:
    s_atom = pd.Series(all_ids, name="id")
    print("\nAtom ids:")
    print("n ids:", len(s_atom), "unique ids:", s_atom.nunique(), "dups:", s_atom.duplicated().sum())

    ids_atom = set(s_atom.unique())
    ids_ins = set(df_insiders["id"].astype(str).unique())
    ids_unf = set(df_unif_old["id"].astype(str).unique())

    print("\nID set comparison:")
    print("Atom - insiders:", len(ids_atom - ids_ins))
    print("Insiders - Atom:", len(ids_ins - ids_atom))
    print("Atom - unif_old:", len(ids_atom - ids_unf))
    print("Unif_old - Atom:", len(ids_unf - ids_atom))

ZIPs: 11
Total atom files: 1312
Workers: 20
[25/1312 atoms] total_entries=12,219 | elapsed=1.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (25/92 atoms)
[50/1312 atoms] total_entries=24,674 | elapsed=2.3s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (50/92 atoms)
[75/1312 atoms] total_entries=37,134 | elapsed=3.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (75/92 atoms)
[100/1312 atoms] total_entries=49,199 | elapsed=3.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (90/92 atoms)
[125/1312 atoms] total_entries=61,650 | elapsed=4.3s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (92/92 atoms)
[150/1312 atoms] total_entries=74,117 | elapsed=4.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (92/92 atoms)
[175/1312 atoms] total_entries=86,576 | elapsed=5.5s | sample_zip=licitacionesPerfilesContratanteCompleto3_202502.zip (92/92 atoms)
[200/1312 atoms] total_entries=98,705 | elapsed=6.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202503.zip (106/111 atoms)
[225/1312 atoms] total_entries=111,144 | elapsed=6.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202503.zip (111/111 atoms)
[250/1312 atoms] total_entries=123,618 | elapsed=7.5s | sample_zip=licitacionesPerfilesContratanteCompleto3_202503.zip (111/111 atoms)
[275/1312 atoms] total_entries=136,082 | elapsed=8.1s | sample_zip=licitacionesPerfilesContratanteCompleto3_202503.zip (111/111 atoms)
[300/1312 atoms] total_entries=148,552 | elapsed=8.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202503.zip (111/111 atoms)
[325/1312 atoms] total_entries=160,967 | elapsed=9.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202504.zip (112/112 atoms)
[350/1312 atoms] total_entries=173,440 | elapsed=9.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202504.zip (112/112 atoms)
[375/1312 atoms] total_entries=185,899 | elapsed=10.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202504.zip (112/112 atoms)
[400/1312 atoms] total_entries=198,362 | elapsed=11.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202504.zip (112/112 atoms)
[425/1312 atoms] total_entries=210,824 | elapsed=12.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202504.zip (112/112 atoms)
[450/1312 atoms] total_entries=222,868 | elapsed=12.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202505.zip (125/127 atoms)
[475/1312 atoms] total_entries=235,321 | elapsed=13.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202505.zip (127/127 atoms)
[500/1312 atoms] total_entries=247,788 | elapsed=13.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202505.zip (127/127 atoms)
[525/1312 atoms] total_entries=260,252 | elapsed=14.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202505.zip (127/127 atoms)
[550/1312 atoms] total_entries=272,720 | elapsed=15.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202505.zip (127/127 atoms)
[575/1312 atoms] total_entries=284,719 | elapsed=15.8s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (128/131 atoms)
[600/1312 atoms] total_entries=297,175 | elapsed=16.5s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (131/131 atoms)
[625/1312 atoms] total_entries=309,635 | elapsed=17.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (131/131 atoms)
[650/1312 atoms] total_entries=322,078 | elapsed=17.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (131/131 atoms)
[675/1312 atoms] total_entries=334,539 | elapsed=18.5s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (131/131 atoms)
[700/1312 atoms] total_entries=347,003 | elapsed=19.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202506.zip (131/131 atoms)
[725/1312 atoms] total_entries=359,208 | elapsed=19.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[750/1312 atoms] total_entries=371,675 | elapsed=20.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[775/1312 atoms] total_entries=384,143 | elapsed=21.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[800/1312 atoms] total_entries=394,938 | elapsed=21.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[825/1312 atoms] total_entries=407,231 | elapsed=22.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[850/1312 atoms] total_entries=419,194 | elapsed=22.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[875/1312 atoms] total_entries=431,292 | elapsed=23.5s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[900/1312 atoms] total_entries=443,365 | elapsed=24.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[925/1312 atoms] total_entries=455,224 | elapsed=24.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[950/1312 atoms] total_entries=467,436 | elapsed=25.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[975/1312 atoms] total_entries=479,812 | elapsed=26.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1000/1312 atoms] total_entries=491,959 | elapsed=26.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1025/1312 atoms] total_entries=504,421 | elapsed=27.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1050/1312 atoms] total_entries=516,616 | elapsed=27.9s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1075/1312 atoms] total_entries=529,084 | elapsed=28.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1100/1312 atoms] total_entries=541,557 | elapsed=29.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1125/1312 atoms] total_entries=554,024 | elapsed=30.0s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1150/1312 atoms] total_entries=566,494 | elapsed=30.6s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1175/1312 atoms] total_entries=578,954 | elapsed=31.2s | sample_zip=licitacionesPerfilesContratanteCompleto3_202507.zip (139/139 atoms)
[1200/1312 atoms] total_entries=591,422 | elapsed=31.8s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)
[1225/1312 atoms] total_entries=603,891 | elapsed=32.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)
[1250/1312 atoms] total_entries=616,364 | elapsed=33.1s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)
[1275/1312 atoms] total_entries=628,845 | elapsed=33.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)
[1300/1312 atoms] total_entries=641,316 | elapsed=34.4s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)
[1312/1312 atoms] total_entries=647,302 | elapsed=34.7s | sample_zip=licitacionesPerfilesContratanteCompleto3_202511.zip (142/142 atoms)

DONE. Total entries: 647302 | elapsed: 34.8s

=== RESUMEN POR ZIP ===
                                                  zip  n_atom_files  \
0   licitacionesPerfilesContratanteCompleto3_20250...            92
1   licitacionesPerfilesContratanteCompleto3_20250...           111
2   licitacionesPerfilesContratanteCompleto3_20250...           112
3   licitacionesPerfilesContratanteCompleto3_20250...           127
4   licitacionesPerfilesContratanteCompleto3_20250...           131
5   licitacionesPerfilesContratanteCompleto3_20250...           139
6   licitacionesPerfilesContratanteCompleto3_20250...            98
7   licitacionesPerfilesContratanteCompleto3_20250...           127
8   licitacionesPerfilesContratanteCompleto3_20251...           118
9   licitacionesPerfilesContratanteCompleto3_20251...           142
10  licitacionesPerfilesContratanteCompleto3_20251...           115

    n_entries  atoms_done
0       45606          92
1       54932         111
2       55492         112
3       63274         127
4       64879         131
5       68808         139
6       47114          98
7       61233         127
8       58034         118
9       70554         142
10      57376         115

Parquet rows:
insiders: 206869 unique ids: 206869
unif_old: 206869 unique ids: 206869

In [18]:
from pathlib import Path
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
import os
from collections import Counter

BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_paths = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def list_atom_files_in_zip(zip_path: Path):
    with zipfile.ZipFile(zip_path, "r") as z:
        return [n for n in z.namelist() if n.lower().endswith(".atom")]

def process_atom_ids(task):
    zip_path_str, atom_name = task
    zip_path = Path(zip_path_str)

    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(atom_name) as f:
            root = ET.parse(f).getroot()

    ids = []
    for entry in list(root):
        if localname(entry.tag) != "entry":
            continue
        for ch in list(entry):
            if localname(ch.tag) == "id":
                ids.append((ch.text or "").strip())
                break
    return zip_path.name, atom_name, ids

# tareas
tasks = []
for zp in zip_paths:
    for a in list_atom_files_in_zip(zp):
        tasks.append((str(zp), a))

MAX_WORKERS = min(20, os.cpu_count() or 1)
PROGRESS_EVERY = 25

t0 = time.time()
counter = Counter()
done = 0

with ProcessPoolExecutor(max_workers=MAX_WORKERS) as ex:
    futures = [ex.submit(process_atom_ids, t) for t in tasks]
    for fut in as_completed(futures):
        _, _, ids = fut.result()
        counter.update(ids)
        done += 1
        if done % PROGRESS_EVERY == 0 or done == len(tasks):
            print(f"[{done}/{len(tasks)}] unique_ids={len(counter):,} elapsed={time.time()-t0:.1f}s")

total_entries = sum(counter.values())
unique_ids = len(counter)
dup_entries = total_entries - unique_ids
print("\nAtom totals:")
print("entries:", total_entries)
print("unique ids:", unique_ids)
print("duplicate entries:", dup_entries)
print("avg entries per id:", total_entries / unique_ids)

# comparar con parquet
df_insiders = pd.read_parquet(BASE / "insiders.parquet", engine="fastparquet")
ids_ins = set(df_insiders["id"].astype(str).unique())

ids_atom = set(counter.keys())
print("\nSet comparison with insiders.parquet:")
print("Atom - insiders:", len(ids_atom - ids_ins))
print("Insiders - Atom:", len(ids_ins - ids_atom))
print("Examples Atom - insiders:", list(sorted(ids_atom - ids_ins))[:5])
print("Examples Insiders - Atom:", list(sorted(ids_ins - ids_atom))[:5])

# opcional: ver los top IDs más repetidos en Atom (para confirmar naturaleza de duplicado)
print("\nTop repeated Atom ids:")
print(counter.most_common(10))

[25/1312] unique_ids=10,613 elapsed=1.8s
[50/1312] unique_ids=19,170 elapsed=2.5s
[75/1312] unique_ids=26,565 elapsed=3.2s
[100/1312] unique_ids=32,486 elapsed=3.9s
[125/1312] unique_ids=37,851 elapsed=4.5s
[150/1312] unique_ids=42,742 elapsed=5.2s
[175/1312] unique_ids=47,464 elapsed=5.8s
[200/1312] unique_ids=51,969 elapsed=6.3s
[225/1312] unique_ids=56,111 elapsed=7.1s
[250/1312] unique_ids=59,999 elapsed=7.6s
[275/1312] unique_ids=64,302 elapsed=8.4s
[300/1312] unique_ids=68,258 elapsed=9.0s
[325/1312] unique_ids=71,759 elapsed=9.6s
[350/1312] unique_ids=75,336 elapsed=10.2s
[375/1312] unique_ids=79,051 elapsed=10.9s
[400/1312] unique_ids=82,854 elapsed=11.5s
[425/1312] unique_ids=86,236 elapsed=12.2s
[450/1312] unique_ids=89,903 elapsed=12.8s
[475/1312] unique_ids=93,466 elapsed=13.5s
[500/1312] unique_ids=97,012 elapsed=14.1s
[525/1312] unique_ids=100,664 elapsed=14.7s
[550/1312] unique_ids=104,035 elapsed=15.4s
[575/1312] unique_ids=107,665 elapsed=16.0s
[600/1312] unique_ids=111,057 elapsed=16.6s
[625/1312] unique_ids=114,576 elapsed=17.4s
[650/1312] unique_ids=118,066 elapsed=17.9s
[675/1312] unique_ids=121,476 elapsed=18.6s
[700/1312] unique_ids=124,929 elapsed=19.2s
[725/1312] unique_ids=128,337 elapsed=20.0s
[750/1312] unique_ids=131,901 elapsed=20.6s
[775/1312] unique_ids=135,290 elapsed=21.2s
[800/1312] unique_ids=138,227 elapsed=21.8s
[825/1312] unique_ids=141,223 elapsed=22.4s
[850/1312] unique_ids=144,369 elapsed=23.0s
[875/1312] unique_ids=147,177 elapsed=23.7s
[900/1312] unique_ids=150,157 elapsed=24.2s
[925/1312] unique_ids=153,364 elapsed=24.9s
[950/1312] unique_ids=156,705 elapsed=25.5s
[975/1312] unique_ids=160,148 elapsed=26.2s
[1000/1312] unique_ids=163,622 elapsed=26.9s
[1025/1312] unique_ids=167,579 elapsed=27.5s
[1050/1312] unique_ids=171,308 elapsed=28.0s
[1075/1312] unique_ids=174,742 elapsed=28.8s
[1100/1312] unique_ids=178,272 elapsed=29.4s
[1125/1312] unique_ids=181,860 elapsed=30.1s
[1150/1312] unique_ids=185,412 elapsed=30.7s
[1175/1312] unique_ids=188,870 elapsed=31.3s
[1200/1312] unique_ids=192,164 elapsed=32.0s
[1225/1312] unique_ids=195,518 elapsed=32.6s
[1250/1312] unique_ids=198,772 elapsed=33.3s
[1275/1312] unique_ids=202,103 elapsed=33.9s
[1300/1312] unique_ids=205,447 elapsed=34.5s
[1312/1312] unique_ids=206,869 elapsed=34.8s

Atom totals:
entries: 647302
unique ids: 206869
duplicate entries: 440433
avg entries per id: 3.1290430175618384

Set comparison with insiders.parquet:
Atom - insiders: 0
Insiders - Atom: 0
Examples Atom - insiders: []
Examples Insiders - Atom: []

Top repeated Atom ids:
[('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/14905679', 149), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/9068460', 55), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16095721', 53), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/17074936', 50), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/17303129', 48), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/11279276', 45), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16597704', 40), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16777059', 37), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/11571214', 32), ('https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16513845', 32)]

## 1.3. Carga básica de datos crudos

In [20]:
from pathlib import Path
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm.auto import tqdm

BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_paths = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def list_atom_files_in_zip(zip_path: Path):
    with zipfile.ZipFile(zip_path, "r") as z:
        return [n for n in z.namelist() if n.lower().endswith(".atom")]

def parse_atom_light(task):
    """
    task: (zip_path_str, atom_name)
    return: list[dict] (1 dict por entry)
    """
    zip_path_str, atom_name = task
    zip_path = Path(zip_path_str)

    with zipfile.ZipFile(zip_path, "r") as z:
        with z.open(atom_name) as f:
            root = ET.parse(f).getroot()

    records = []
    for entry in list(root):
        if localname(entry.tag) != "entry":
            continue

        rec = {
            "id": None,
            "link": None,
            "summary": None,
            "title": None,
            "updated": None,
            "_source_zip": zip_path.name,
            "_source_atom": atom_name,
            "_contract_folder_status_xml": None,
        }

        for ch in list(entry):
            ln = localname(ch.tag)
            if ln == "id":
                rec["id"] = (ch.text or "").strip()
            elif ln == "updated":
                rec["updated"] = (ch.text or "").strip()
            elif ln == "title":
                rec["title"] = (ch.text or "").strip()
            elif ln == "summary":
                rec["summary"] = (ch.text or "").strip()
            elif ln == "link":
                rec["link"] = ch.attrib.get("href")
            elif ln == "ContractFolderStatus":
                rec["_contract_folder_status_xml"] = ET.tostring(ch, encoding="unicode")

        records.append(rec)

    return records

# tareas (zip, atom)
tasks = []
for zp in zip_paths:
    for atom in list_atom_files_in_zip(zp):
        tasks.append((str(zp), atom))

MAX_WORKERS = min(20, os.cpu_count() or 1)

all_records = []
with ProcessPoolExecutor(max_workers=MAX_WORKERS) as ex:
    futures = [ex.submit(parse_atom_light, t) for t in tasks]
    for fut in tqdm(as_completed(futures), total=len(futures), desc="Parsing .atom"):
        all_records.extend(fut.result())

df_atom_light = pd.DataFrame(all_records)
print("df_atom_light:", df_atom_light.shape)

/home/jarenas/github/PLACEingest/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Parsing .atom: 100%|███████████████████████████████████████████████████████████████████████████████| 1312/1312 [00:46<00:00, 28.42it/s]

df_atom_light: (647302, 8)

In [21]:
# Parsear updated como datetime (maneja timezone)
df_atom_light["updated_dt"] = pd.to_datetime(df_atom_light["updated"], errors="coerce", utc=True)

# idx del registro más reciente por id
idx = df_atom_light.groupby("id")["updated_dt"].idxmax()

df_atom_latest = df_atom_light.loc[idx].copy().drop(columns=["updated_dt"])
df_atom_latest.reset_index(drop=True, inplace=True)

print("df_atom_latest:", df_atom_latest.shape)
print("unique ids:", df_atom_latest["id"].nunique())

df_atom_latest: (206869, 8)
unique ids: 206869

In [22]:
df_insiders = pd.read_parquet(BASE / "insiders.parquet", engine="fastparquet")

print("parquet rows:", df_insiders.shape[0], "unique:", df_insiders["id"].nunique())
print("atom_latest rows:", df_atom_latest.shape[0], "unique:", df_atom_latest["id"].nunique())

# sets (debería ser 0 y 0 si has procesado los mismos meses)
ids_atom = set(df_atom_latest["id"].astype(str).unique())
ids_parq = set(df_insiders["id"].astype(str).unique())
print("Atom - parquet:", len(ids_atom - ids_parq))
print("Parquet - Atom:", len(ids_parq - ids_atom))

parquet rows: 206869 unique: 206869
atom_latest rows: 206869 unique: 206869
Atom - parquet: 0
Parquet - Atom: 0

In [24]:
df_atom_latest[:10]

,id,link,summary,title,updated,_source_zip,_source_atom,_contract_folder_status_xml
0,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: EC22-C03-02760; Órgano de Contr...,"Control de la calidad de agua potable, y preve...",2025-03-12T09:00:00.000+01:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
1,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 2022/D22200/006-302/00001; Órga...,servicio de atención telefónica en materia tri...,2025-11-20T08:20:48.669+01:00,licitacionesPerfilesContratanteCompleto3_20251...,licitacionesPerfilesContratanteCompleto3_20251...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
2,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 2022/017.SUM.ABR.MC; Órgano de ...,Suministro de licencia y alojamiento del ecos...,2025-11-17T09:00:00.000+01:00,licitacionesPerfilesContratanteCompleto3_20251...,licitacionesPerfilesContratanteCompleto3_20251...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
3,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: CN-01/2022; Órgano de Contratac...,L'objecte del contracte és la cessió a tercers...,2025-02-04T10:12:01.069+01:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
4,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: A-12/22; Órgano de Contratación...,Servicio de gestión y franqueo de corresponden...,2025-06-09T17:29:47.141+02:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
5,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 22 036 SR JD AB OA31; Órgano de...,Servicio de mantenimiento de servidores corpor...,2025-07-21T12:10:17.073+02:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
6,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 8480/2022; Órgano de Contrataci...,"Servicio iluminación, Sonorización, Carga y De...",2025-06-26T11:57:51.505+02:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
7,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: 2022-036-A; Órgano de Contratac...,Contrato mixto de servicios y obras de instala...,2025-09-19T11:52:48.441+02:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
8,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: M220032; Órgano de Contratación...,Sistema de gestión informático del servicio de...,2025-03-13T11:33:32.076+01:00,licitacionesPerfilesContratanteCompleto3_20250...,licitacionesPerfilesContratanteCompleto3_20250...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."
9,https://contrataciondelestado.es/sindicacion/l...,https://contrataciondelestado.es/wps/poc?uri=d...,Id licitación: CNMY22/DGJ/32; Órgano de Contra...,Construcción de la Ciudad de la Justicia de Al...,2025-12-04T09:00:00.000+01:00,licitacionesPerfilesContratanteCompleto3_20251...,licitacionesPerfilesContratanteCompleto3_20251...,"<ns0:ContractFolderStatus xmlns:ns0=""urn:dgpe:..."

# 2. Transformación y Selección de datos

## 2.1. Función para leer los datos y consolidar con lo que ya hubiera

### 2.1.1. Versión monocore

In [31]:
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Union, Optional, Dict, Any, List
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
from tqdm.auto import tqdm


def _localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag


def _iter_input_paths(sources: Union[str, Path, Iterable[Union[str, Path]]]) -> List[Path]:
    """
    Normaliza 'sources' a una lista de Paths:
    - acepta Path/str, lista de Path/str
    - acepta directorios (recursivo: *.zip, *.atom)
    - acepta globs en str (p.ej. '/ruta/*.zip')
    """
    if isinstance(sources, (str, Path)):
        sources = [sources]

    out: List[Path] = []
    for s in sources:
        p = Path(s)
        if isinstance(s, str) and any(ch in s for ch in ["*", "?", "[", "]"]):
            out.extend([Path(x) for x in sorted(Path().glob(s))])
            continue

        if p.is_dir():
            out.extend(sorted(p.rglob("*.zip")))
            out.extend(sorted(p.rglob("*.atom")))
        else:
            out.append(p)

    # de-dup preservando orden
    seen = set()
    deduped = []
    for p in out:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            deduped.append(rp)
    return deduped


def _parse_atom_fileobj_to_latest_map(fileobj, latest_by_id: Dict[str, Dict[str, Any]]) -> None:
    """
    Lee un ATOM (XML) desde un file-like y actualiza latest_by_id[id] con el registro más reciente por updated.
    Extrae: id, title, summary, updated, link
    """
    root = ET.parse(fileobj).getroot()

    for entry in list(root):
        if _localname(entry.tag) != "entry":
            continue

        rec = {"id": None, "title": None, "summary": None, "updated": None, "link": None}

        for ch in list(entry):
            ln = _localname(ch.tag)
            if ln == "id":
                rec["id"] = (ch.text or "").strip()
            elif ln == "title":
                rec["title"] = (ch.text or "").strip()
            elif ln == "summary":
                rec["summary"] = (ch.text or "").strip()
            elif ln == "updated":
                rec["updated"] = (ch.text or "").strip()
            elif ln == "link":
                # en estos feeds suele haber un único link con href
                if rec["link"] is None:
                    rec["link"] = ch.attrib.get("href")

        if not rec["id"] or not rec["updated"]:
            continue

        upd = pd.to_datetime(rec["updated"], errors="coerce", utc=True)
        if pd.isna(upd):
            continue

        prev = latest_by_id.get(rec["id"])
        if prev is None or upd > prev["_updated_dt"]:
            rec["_updated_dt"] = upd
            latest_by_id[rec["id"]] = rec


def _iter_atom_jobs(paths: list[Path]):
    """
    Genera trabajos:
    - ("zip", zip_path, atom_name)
    - ("atom", atom_path, None)
    """
    for p in paths:
        if p.suffix.lower() == ".zip":
            with zipfile.ZipFile(p, "r") as z:
                atom_names = [n for n in z.namelist() if n.lower().endswith(".atom")]
            for atom_name in atom_names:
                yield ("zip", p, atom_name)
        elif p.suffix.lower() == ".atom":
            yield ("atom", p, None)


def _ingest_sources_to_latest_map(paths: List[Path], show_progress: bool = True) -> Dict[str, Dict[str, Any]]:
    """
    Procesa paths (zip/atom) y devuelve mapa id->registro_latest.
    """
    latest_by_id: Dict[str, Dict[str, Any]] = {}

    jobs = list(_iter_atom_jobs(paths))
    it = tqdm(jobs, desc="Parsing .atom", unit="atom") if show_progress else jobs

    # Cache de zipfile abiertos por ZIP para no reabrirlos cada atom (acelera bastante)
    zcache: Dict[Path, zipfile.ZipFile] = {}
    try:
        for kind, p, atom_name in it:
            if kind == "zip":
                zf = zcache.get(p)
                if zf is None:
                    zf = zipfile.ZipFile(p, "r")
                    zcache[p] = zf
                with zf.open(atom_name) as f:
                    _parse_atom_fileobj_to_latest_map(f, latest_by_id)
            else:
                with p.open("rb") as f:
                    _parse_atom_fileobj_to_latest_map(f, latest_by_id)
    finally:
        for zf in zcache.values():
            zf.close()

    return latest_by_id
    

def _latest_map_to_df(latest_by_id: Dict[str, Dict[str, Any]]) -> pd.DataFrame:
    df = pd.DataFrame(latest_by_id.values())
    if df.empty:
        return df
    # limpiar columna interna
    df = df.drop(columns=["_updated_dt"], errors="ignore")
    # asegurar tipos
    df["id"] = df["id"].astype(str)
    # orden opcional (por updated desc)
    df["_updated_dt"] = pd.to_datetime(df["updated"], errors="coerce", utc=True)
    df = df.sort_values("_updated_dt", ascending=False).drop(columns=["_updated_dt"])
    df = df.reset_index(drop=True)
    return df


def build_latest_entries(
    sources: Union[str, Path, Iterable[Union[str, Path]]],
    parquet_path: Optional[Union[str, Path]] = None,
    *,
    show_progress: bool = True,
) -> pd.DataFrame:
    """
    - sources: fichero(s) zip/atom, carpeta, glob, o lista mezclada.
    - parquet_path (opcional): si se pasa, consolida con lo existente y guarda resultado.
      Criterio siempre: conservar por 'id' la fila con updated más reciente.
    - Devuelve el DataFrame consolidado.
    """
    paths = _iter_input_paths(sources)

    # 1) ingest de sources -> latest map
    latest_map = _ingest_sources_to_latest_map(paths, show_progress=show_progress)

    # 2) si hay parquet, consolidar
    if parquet_path is not None:
        parquet_path = Path(parquet_path)

        if parquet_path.exists():
            df_old = pd.read_parquet(parquet_path, engine="fastparquet")
            # consolidar df_old dentro del mismo mapa (sin reparsear XML)
            # usamos el mismo criterio de updated
            df_old = df_old.copy()
            df_old["_updated_dt"] = pd.to_datetime(df_old["updated"], errors="coerce", utc=True)

            for r in df_old.itertuples(index=False):
                rid = getattr(r, "id", None)
                upd = getattr(r, "_updated_dt", None)
                if rid is None or pd.isna(upd):
                    continue

                rec = {
                    "id": str(rid),
                    "title": getattr(r, "title", None),
                    "summary": getattr(r, "summary", None),
                    "updated": getattr(r, "updated", None),
                    "link": getattr(r, "link", None),
                    "_updated_dt": upd,
                }

                prev = latest_map.get(rec["id"])
                if prev is None or rec["_updated_dt"] > prev["_updated_dt"]:
                    latest_map[rec["id"]] = rec

        # 3) construir df final y guardar
        df_final = _latest_map_to_df(latest_map)
        parquet_path.parent.mkdir(parents=True, exist_ok=True)
        df_final.to_parquet(parquet_path, engine="fastparquet", index=False)
        return df_final

    # sin parquet: solo dataframe
    return _latest_map_to_df(latest_map)

### 2.1.2. Versión paralelo

#### 2.1.2.1. Diccionario con los nombres finales de las columnas

In [101]:
COLUMN_MAP = {
    # Datos del expediente
    "estado": "estado",
    "expediente": "expediente",
    "objeto": "objeto",
    "valor_estimado": "valor_estimado",
    "presupuesto_sin_iva": "presupuesto_sin_iva",
    "presupuesto_con_iva": "presupuesto_con_iva",
    "duracion_dias": "duracion_dias",
    "cpv_list": "cpv_list",
    "pliego_tecnico_uri": "pliego_tecnico_URI",
    "pliego_tecnico_filename": "pliego_tecnico_filename",
    "pliego_admin_uri": "pliego_admin_URI",
    "pliego_admin_filename": "pliego_admin_filename",
    "ted_uuid": "TED id",

    # Datos geográficos 
    "subentidad_nacional": "subentidad_nacional",
    "codigo_subentidad_territorial": "codigo_subentidad_territorial",

    # Contiene el número y objetivo de cada lote
    "lotes": "lotes",

    # Sobre la tramitación y Administración que contrata
    "tipo_procedimiento": "tipo_procedimiento",
    "tramitacion": "tramitacion",
    "over_threshold": "sobre_umbral",
    "organo_nombre": "organo_nombre",
    "organo_id": "organo_id",
    "plazo_presentacion": "plazo_presentacion",

    # TenderResult (normalizados)
    "resultado": "resultado",
    "fecha_acuerdo": "fecha_acuerdo",
    "ofertas_recibidas": "ofertas_recibidas",
    "ofertas_pymes": "ofertas_pymes",
    "adjudicatario_nombre": "adjudicatario_nombre",
    "identificador": "identificador",
    "adjudicatario_pyme": "adjudicatario_pyme",
    "adjudicatario_ute": "adjudicatario_ute",
    "importe_total_sin_iva": "importe_ofertado_sin_iva",
    "importe_total_con_iva": "importe_ofertado_con_iva",
}

#### 2.1.2.2. Helpers XML + normalización

In [69]:
import xml.etree.ElementTree as ET
from datetime import datetime
from urllib.parse import urlparse
from pathlib import Path
import zipfile
import pandas as pd
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm import tqdm

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_child_by_localname(elem, name):
    for ch in list(elem):
        if localname(ch.tag) == name:
            return ch
    return None

def find_first_text_from(elem, path):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return (cur.text or "").strip()

def find_all_texts_from(elem, path):
    nodes = [elem]
    for name in path:
        nxt = []
        for n in nodes:
            for ch in list(n):
                if localname(ch.tag) == name:
                    nxt.append(ch)
        nodes = nxt
    return [(n.text or "").strip() for n in nodes if (n.text or "").strip()]

# Normalización de los campos de presupuestos
def to_float(x):
    try:
        return float(x)
    except Exception:
        return None

# Normalización del campo "Plazo de ejecución"
def duration_to_days(start, end, duration, unit):
    # prioridad: si hay start+end -> diff días
    if start and end:
        try:
            d0 = datetime.fromisoformat(start)
            d1 = datetime.fromisoformat(end)
            return (d1 - d0).days
        except Exception:
            pass

    # si hay duration + unit
    if duration and unit:
        try:
            v = float(duration)
            unit = unit.upper()
            if unit == "DAY":
                return int(v)
            if unit == "MON":
                return int(v * 30)
            if unit == "ANN":
                return int(v * 365)
        except Exception:
            pass

    return None

#### 2.1.2.3. Extractor de campos

In [70]:
def extract_normalized_fields(entry):
    cfs = find_child_by_localname(entry, "ContractFolderStatus")
    if cfs is None:
        return None

    # campos base
    estado = find_first_text_from(cfs, ["ContractFolderStatusCode"])
    expediente = find_first_text_from(cfs, ["ContractFolderID"])
    objeto = find_first_text_from(cfs, ["ProcurementProject", "Name"])

    valor_estimado = to_float(find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "EstimatedOverallContractAmount"]))
    presupuesto_sin_iva = to_float(find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "TaxExclusiveAmount"]))
    presupuesto_con_iva = to_float(find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "TotalAmount"]))

    # plazo -> días
    start = find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "StartDate"])
    end = find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "EndDate"])
    duration = find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "DurationMeasure"])
    unit = None
    pp = find_child_by_localname(find_child_by_localname(cfs, "ProcurementProject"), "PlannedPeriod")
    if pp is not None:
        dm = find_child_by_localname(pp, "DurationMeasure")
        if dm is not None:
            unit = dm.attrib.get("unitCode")

    duracion_dias = duration_to_days(start, end, duration, unit)

    # CPV
    cpv_list = find_all_texts_from(cfs, ["ProcurementProject", "RequiredCommodityClassification", "ItemClassificationCode"])

    # pliegos
    pliego_tecnico_uri = find_first_text_from(cfs, ["LegalDocumentReference", "Attachment", "ExternalReference", "URI"])
    pliego_tecnico_filename = find_first_text_from(cfs, ["LegalDocumentReference", "ID"])
    
    pliego_admin_uri = find_first_text_from(cfs, ["TechnicalDocumentReference", "Attachment", "ExternalReference", "URI"])
    pliego_admin_filename = find_first_text_from(cfs, ["TechnicalDocumentReference", "ID"])

    # TED UUID
    ted_uuid = None
    for ch in list(cfs):
        if localname(ch.tag) == "UUID" and ch.attrib.get("schemeName") == "TED":
            ted_uuid = (ch.text or "").strip()

    return {
        "estado": estado,
        "expediente": expediente,
        "objeto": objeto,
        "valor_estimado": valor_estimado,
        "presupuesto_sin_iva": presupuesto_sin_iva,
        "presupuesto_con_iva": presupuesto_con_iva,
        "duracion_dias": duracion_dias,
        "cpv_list": cpv_list,
        "pliego_tecnico_uri": pliego_tecnico_uri,
        "pliego_tecnico_filename": pliego_tecnico_filename,
        "pliego_admin_uri": pliego_admin_uri,
        "pliego_admin_filename": pliego_admin_filename,
        "ted_uuid": ted_uuid,
    }

#### 2.1.2.4. Extracción multicore de todo

In [71]:
def extract_atom_fields(entry):
    atom = {"title": None, "summary": None, "link": None}
    for ch in list(entry):
        name = localname(ch.tag)
        if name == "title":
            atom["title"] = (ch.text or "").strip()
        elif name == "summary":
            atom["summary"] = (ch.text or "").strip()
        elif name == "link":
            atom["link"] = ch.attrib.get("href")
    return atom
    

def process_zip_for_latest(zip_path):
    latest = {}
    with zipfile.ZipFile(zip_path, "r") as z:
        atoms = [n for n in z.namelist() if n.lower().endswith(".atom")]
        for atom in atoms:
            with z.open(atom) as f:
                root = ET.parse(f).getroot()

            for entry in list(root):
                eid = None
                updated = None
                for ch in list(entry):
                    if localname(ch.tag) == "id":
                        eid = (ch.text or "").strip()
                    elif localname(ch.tag) == "updated":
                        updated = (ch.text or "").strip()

                if not eid or not updated:
                    continue

                atom_fields = extract_atom_fields(entry)
                rec = extract_normalized_fields(entry)
                if rec is None:
                    continue
                
                latest[eid] = {
                    "id": eid,
                    "updated": updated,
                    **atom_fields,
                    **rec,
                    "_updated": updated
                }

    return latest

In [72]:
def build_latest_entries_multicore(sources, parquet_path=None, max_workers=8, show_progress=True):
    paths = [Path(p) for p in sources]

    merged = {}

    with ProcessPoolExecutor(max_workers=max_workers) as ex:
        futures = [ex.submit(process_zip_for_latest, p) for p in paths]
        it = as_completed(futures)
        if show_progress:
            it = tqdm(it, total=len(futures), desc="Zips")

        for fut in it:
            latest_part = fut.result()
            for eid, rec in latest_part.items():
                prev = merged.get(eid)
                if (prev is None) or (rec["_updated"] > prev["_updated"]):
                    merged[eid] = rec

    df = pd.DataFrame([v for v in merged.values()]).drop(columns=["_updated"])

    # renombrar columnas según COLUMN_MAP
    df = df.rename(columns=COLUMN_MAP)

    if parquet_path:
        parquet_path = Path(parquet_path)
        if parquet_path.exists():
            old = pd.read_parquet(parquet_path, engine="fastparquet")
            df = (
                pd.concat([old, df], ignore_index=True)
                .sort_values("updated")
                .drop_duplicates(subset=["id"], keep="last")
            )
        df.to_parquet(parquet_path, index=False, engine="fastparquet")

    return df

In [73]:
BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_paths = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

df_latest = build_latest_entries_multicore(
    zip_paths,
    parquet_path="/home/jarenas/Datasets/PLACE/insiders_unificado_v2.parquet",
    max_workers=12,
    show_progress=True
)

print(len(df_latest))
display(df_latest.head())

Zips: 100%|████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [02:25<00:00, 13.25s/it]

,id,updated,title,summary,link,estado,expediente,objeto,valor_estimado,presupuesto_sin_iva,presupuesto_con_iva,duracion_dias,cpv_list,pliego_tecnico_URI,pliego_tecnico_filename,pliego_admin_URI,pliego_admin_filename,TED id
0,https://contrataciondelestado.es/sindicacion/l...,2025-02-27T12:00:22.565+01:00,Mejora del camino municipal de Almieiras a río...,Id licitación: 2024/C003/000002; Órgano de Con...,https://contrataciondelestado.es/wps/poc?uri=d...,ADJ,2024/C003/000002,Mejora del camino municipal de Almieiras a río...,74325.09,74325.09,89933.36,90.0,[45233140],https://contrataciondelestado.es/FileSystem/se...,PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT.pdf,None
1,https://contrataciondelestado.es/sindicacion/l...,2025-12-02T09:16:30.234+01:00,Actividades de sensibilización e información a...,Id licitación: 2024_0127; Órgano de Contrataci...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,2024_0127,Actividades de sensibilización e información a...,1241295.50,744777.30,901180.53,1095.0,"[80550000, 80540000, 92000000]",https://contrataciondelestado.es/FileSystem/se...,14 PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,06 ppt.pdf,b9110180-dd40-4b93-b183-6ae2dfb91718
2,https://contrataciondelestado.es/sindicacion/l...,2025-05-23T08:18:21.152+02:00,Obra de reparación e impermeabilización de ter...,Id licitación: PAS 481/2024; Órgano de Contrat...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,PAS 481/2024,Obra de reparación e impermeabilización de ter...,202521.08,184110.08,222773.20,150.0,[45215140],https://contrataciondelestado.es/FileSystem/se...,PCAP OBRA SIMPLIFICADO NO REAC.pdf,https://contrataciondelestado.es/FileSystem/se...,Pliego_impermeabilizacion.pdf,None
3,https://contrataciondelestado.es/sindicacion/l...,2025-06-12T12:06:19.195+02:00,Obra para la impermeabilización de cubiertas ...,Id licitación: PAS 333/2025 TA; Órgano de Cont...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,PAS 333/2025 TA,Obra para la impermeabilización de cubiertas ...,269301.05,244819.14,269301.16,120.0,[45261420],https://contrataciondelestado.es/FileSystem/se...,10 PLIEGO ABIERTO simplif OBRAS .pdf,https://contrataciondelestado.es/FileSystem/se...,PPT Impermeabilizacion Cubiertas_firmado.zip,None
4,https://contrataciondelestado.es/sindicacion/l...,2025-02-27T12:00:08.272+01:00,Servicio de asistencia técnica en la administr...,Id licitación: 2023/00092; Órgano de Contratac...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,2023/00092,Servicio de asistencia técnica en la administr...,82000.00,41000.00,49610.00,360.0,[72514000],https://contrataciondelestado.es/wps/wcm/conne...,20240202_2_PCAP.pdf,https://contrataciondelestado.es/wps/wcm/conne...,20240202_1_PPT_revisado.pdf,None

#### 2.1.2.X [DEPRECATED] Código multicore para la extracción únicamente de los datos generales del entry

In [39]:
from __future__ import annotations

from pathlib import Path
from typing import Iterable, Union, Optional, Dict, Any, List, Tuple
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
import os
from concurrent.futures import ProcessPoolExecutor, as_completed
from tqdm.auto import tqdm
from glob import glob


def _localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag


def _iter_input_paths(sources):
    if isinstance(sources, (str, Path)):
        sources = [sources]

    out = []
    for s in sources:
        if isinstance(s, str) and any(ch in s for ch in ["*", "?", "[", "]"]):
            out.extend([Path(x) for x in sorted(glob(s))])
            continue

        p = Path(s)
        if p.is_dir():
            out.extend(sorted(p.rglob("*.zip")))
            out.extend(sorted(p.rglob("*.atom")))
        else:
            out.append(p)

    seen = set()
    deduped = []
    for p in out:
        rp = p.resolve()
        if rp not in seen:
            seen.add(rp)
            deduped.append(rp)
    return deduped


def _iter_atom_jobs(paths: List[Path]) -> List[Tuple[str, str, Optional[str]]]:
    """
    Devuelve lista de jobs:
      - ("zip", "<zip_path>", "<atom_name_inside_zip>")
      - ("atom", "<atom_file_path>", None)
    """
    jobs: List[Tuple[str, str, Optional[str]]] = []
    for p in paths:
        if p.suffix.lower() == ".zip":
            with zipfile.ZipFile(p, "r") as z:
                atom_names = [n for n in z.namelist() if n.lower().endswith(".atom")]
            for atom_name in atom_names:
                jobs.append(("zip", str(p), atom_name))
        elif p.suffix.lower() == ".atom":
            jobs.append(("atom", str(p), None))
    return jobs


def _parse_one_atom_job(job: Tuple[str, str, Optional[str]]) -> Dict[str, Dict[str, Any]]:
    """
    Procesa UN .atom (suelo o dentro de zip) y devuelve un dict:
      id -> {"id","title","summary","updated","link","_updated_dt"}
    Mantiene solo el latest por id dentro de ese atom.
    """
    kind, path_str, atom_name = job

    if kind == "zip":
        with zipfile.ZipFile(path_str, "r") as z:
            with z.open(atom_name) as f:
                root = ET.parse(f).getroot()
    else:
        with open(path_str, "rb") as f:
            root = ET.parse(f).getroot()

    latest: Dict[str, Dict[str, Any]] = {}

    for entry in list(root):
        if _localname(entry.tag) != "entry":
            continue

        rec = {"id": None, "title": None, "summary": None, "updated": None, "link": None}

        for ch in list(entry):
            ln = _localname(ch.tag)
            if ln == "id":
                rec["id"] = (ch.text or "").strip()
            elif ln == "title":
                rec["title"] = (ch.text or "").strip()
            elif ln == "summary":
                rec["summary"] = (ch.text or "").strip()
            elif ln == "updated":
                rec["updated"] = (ch.text or "").strip()
            elif ln == "link":
                if rec["link"] is None:
                    rec["link"] = ch.attrib.get("href")

        if not rec["id"] or not rec["updated"]:
            continue

        upd = pd.to_datetime(rec["updated"], errors="coerce", utc=True)
        if pd.isna(upd):
            continue

        prev = latest.get(rec["id"])
        if prev is None or upd > prev["_updated_dt"]:
            rec["_updated_dt"] = upd
            latest[rec["id"]] = rec

    return latest


def _merge_latest_maps(dst: Dict[str, Dict[str, Any]], src: Dict[str, Dict[str, Any]]) -> None:
    for k, rec in src.items():
        prev = dst.get(k)
        if prev is None or rec["_updated_dt"] > prev["_updated_dt"]:
            dst[k] = rec


def _latest_map_to_df(latest_by_id: Dict[str, Dict[str, Any]]) -> pd.DataFrame:
    df = pd.DataFrame(latest_by_id.values())
    if df.empty:
        return df
    df = df.drop(columns=["_updated_dt"], errors="ignore")
    df["id"] = df["id"].astype(str)
    # orden opcional por updated desc
    tmp = pd.to_datetime(df["updated"], errors="coerce", utc=True)
    df = df.assign(_tmp=tmp).sort_values("_tmp", ascending=False).drop(columns=["_tmp"])
    return df.reset_index(drop=True)


def _ingest_sources_to_latest_map_multicore(
    paths: List[Path],
    *,
    show_progress: bool = True,
    max_workers: Optional[int] = None,
) -> Dict[str, Dict[str, Any]]:
    jobs = _iter_atom_jobs(paths)
    if not jobs:
        return {}

    if max_workers is None:
        max_workers = min(20, os.cpu_count() or 1)

    latest_by_id: Dict[str, Dict[str, Any]] = {}

    with ProcessPoolExecutor(max_workers=max_workers) as ex:
        futures = [ex.submit(_parse_one_atom_job, job) for job in jobs]
        it = as_completed(futures)
        if show_progress:
            it = tqdm(it, total=len(futures), desc="Parsing .atom", unit="atom")

        for fut in it:
            local_map = fut.result()
            _merge_latest_maps(latest_by_id, local_map)

    return latest_by_id


def build_latest_entries(
    sources: Union[str, Path, Iterable[Union[str, Path]]],
    parquet_path: Optional[Union[str, Path]] = None,
    *,
    show_progress: bool = True,
    max_workers: Optional[int] = None,
) -> pd.DataFrame:
    """
    Multicore por .atom. Conserva la entrada más reciente por id (updated max).
    Si parquet_path:
      - si no existe, crea
      - si existe, lee y consolida (latest por id)
    Devuelve el DF consolidado.
    """
    paths = _iter_input_paths(sources)

    # 1) ingest multicore
    latest_map = _ingest_sources_to_latest_map_multicore(
        paths, show_progress=show_progress, max_workers=max_workers
    )

    # 2) consolidación con parquet (si aplica)
    if parquet_path is not None:
        parquet_path = Path(parquet_path)

        if parquet_path.exists():
            df_old = pd.read_parquet(parquet_path, engine="fastparquet").copy()
            df_old["_updated_dt"] = pd.to_datetime(df_old["updated"], errors="coerce", utc=True)

            for r in df_old.itertuples(index=False):
                rid = getattr(r, "id", None)
                upd = getattr(r, "_updated_dt", None)
                if rid is None or pd.isna(upd):
                    continue

                rec = {
                    "id": str(rid),
                    "title": getattr(r, "title", None),
                    "summary": getattr(r, "summary", None),
                    "updated": getattr(r, "updated", None),
                    "link": getattr(r, "link", None),
                    "_updated_dt": upd,
                }

                prev = latest_map.get(rec["id"])
                if prev is None or rec["_updated_dt"] > prev["_updated_dt"]:
                    latest_map[rec["id"]] = rec

        df_final = _latest_map_to_df(latest_map)
        parquet_path.parent.mkdir(parents=True, exist_ok=True)
        df_final.to_parquet(parquet_path, engine="fastparquet", index=False)
        return df_final

    return _latest_map_to_df(latest_map)

#### Inspección de valores concretos

In [44]:
df_latest = df_new

In [48]:
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import pandas as pd

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_child_by_localname(elem, name):
    for ch in list(elem):
        if localname(ch.tag) == name:
            return ch
    return None

def find_first_text_from(elem, path):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return (cur.text or "").strip()

def find_all_texts_from(elem, path):
    nodes = [elem]
    for name in path:
        nxt = []
        for n in nodes:
            for ch in list(n):
                if localname(ch.tag) == name:
                    nxt.append(ch)
        nodes = nxt
    return [(n.text or "").strip() for n in nodes if (n.text or "").strip()]

def extract_fields_from_entry(entry):
    cfs = find_child_by_localname(entry, "ContractFolderStatus")
    if cfs is None:
        return {}

    row = {
        "estado": find_first_text_from(cfs, ["ContractFolderStatusCode"]),
        "expediente": find_first_text_from(cfs, ["ContractFolderID"]),
        "objeto": find_first_text_from(cfs, ["ProcurementProject", "Name"]),
        "valor_estimado": find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "EstimatedOverallContractAmount"]),
        "presupuesto_sin_iva": find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "TaxExclusiveAmount"]),
        "presupuesto_con_iva": find_first_text_from(cfs, ["ProcurementProject", "BudgetAmount", "TotalAmount"]),
        "plazo_inicio": find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "StartDate"]),
        "plazo_fin": find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "EndDate"]),
        "plazo_duracion": find_first_text_from(cfs, ["ProcurementProject", "PlannedPeriod", "DurationMeasure"]),
        "cpv_list": find_all_texts_from(cfs, ["ProcurementProject", "RequiredCommodityClassification", "ItemClassificationCode"]),
        "pliego_tecnico_uri": find_first_text_from(cfs, ["LegalDocumentReference", "Attachment", "ExternalReference", "URI"]),
        "pliego_tecnico_id": find_first_text_from(cfs, ["LegalDocumentReference", "ID"]),
        "pliego_admin_uri": find_first_text_from(cfs, ["TechnicalDocumentReference", "Attachment", "ExternalReference", "URI"]),
        "pliego_admin_id": find_first_text_from(cfs, ["TechnicalDocumentReference", "ID"]),
        "ted_uuid": None,
    }

    for ch in list(cfs):
        if localname(ch.tag) == "UUID" and ch.attrib.get("schemeName") == "TED":
            row["ted_uuid"] = (ch.text or "").strip()

    return row


def inspect_first_atoms(base_dir, max_entries=2000):
    base = Path(base_dir)
    zip_files = sorted(base.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

    rows = []
    n_entries = 0

    for zp in zip_files:
        with zipfile.ZipFile(zp, "r") as z:
            atoms = [n for n in z.namelist() if n.lower().endswith(".atom")]
            if not atoms:
                continue

            atom = atoms[0]   # solo el primer atom del zip
            with z.open(atom) as f:
                root = ET.parse(f).getroot()

            for entry in list(root):
                row = extract_fields_from_entry(entry)
                rows.append(row)
                n_entries += 1

                if n_entries >= max_entries:
                    return pd.DataFrame(rows)

            break  # solo primer zip si quieres aún más rápido

    return pd.DataFrame(rows)


df_inspect = inspect_first_atoms("/home/jarenas/Datasets/PLACE/2025", max_entries=2000)
display(df_inspect.head(20))
display(df_inspect.sample(10))

,estado,expediente,objeto,valor_estimado,presupuesto_sin_iva,presupuesto_con_iva,plazo_inicio,plazo_fin,plazo_duracion,cpv_list,pliego_tecnico_uri,pliego_tecnico_id,pliego_admin_uri,pliego_admin_id,ted_uuid
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,ADJ,2024/C003/000002,Mejora del camino municipal de Almieiras a río...,74325.09,74325.09,89933.36,None,None,3,[45233140],https://contrataciondelestado.es/FileSystem/se...,PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT.pdf,None
8,EV,2024_0127,Actividades de sensibilización e información a...,1241295.5,744777.3,901180.53,2025-09-21,None,3,"[80550000, 92000000, 80540000]",https://contrataciondelestado.es/FileSystem/se...,14 PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,06 ppt.pdf,b9110180-dd40-4b93-b183-6ae2dfb91718
9,EV,PAS 481/2024,Obra de reparación e impermeabilización de ter...,202521.08,184110.08,222773.2,None,None,5,[45215140],https://contrataciondelestado.es/FileSystem/se...,PCAP OBRA SIMPLIFICADO NO REAC.pdf,https://contrataciondelestado.es/FileSystem/se...,Pliego_impermeabilizacion.pdf,None
10,EV,PAS 333/2025 TA,Obra para la impermeabilización de cubiertas ...,269301.05,244819.14,269301.16,None,None,4,[45261420],https://contrataciondelestado.es/FileSystem/se...,10 PLIEGO ABIERTO simplif OBRAS .pdf,https://contrataciondelestado.es/FileSystem/se...,PPT Impermeabilizacion Cubiertas_firmado.zip,None
11,RES,2023/00092,Servicio de asistencia técnica en la administr...,82000,41000,49610,None,None,12,[72514000],https://contrataciondelestado.es/wps/wcm/conne...,20240202_2_PCAP.pdf,https://contrataciondelestado.es/wps/wcm/conne...,20240202_1_PPT_revisado.pdf,None
12,PUB,386/2024/CMA,Medidas de acompañamiento social a los partici...,167992,167992,174711.68,None,None,3,[75310000],https://contrataciondelestado.es/FileSystem/se...,PCAP 386 2024.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT 386 2024.pdf,None
13,PUB,OBRAS-05/2024,Intervenciones de protección y puesta en valor...,667809.01,667809.01,808048.9,None,None,4,[45454100],https://contrataciondelestado.es/FileSystem/se...,Pliego administrativo torreparedones.pdf,https://contrataciondelestado.es/FileSystem/se...,Proyecto Torreparedones.pdf,None
14,EV,44/2025,Remodelación del complejo de la Piscina Municipal,321673.05,321673.05,389224.39,None,None,4,"[45212212, 45200000]",https://contrataciondelestado.es/FileSystem/se...,pcap piscina municipal.pdf,https://contrataciondelestado.es/FileSystem/se...,ppt piscina.pdf,None
15,EV,PAS 668/2024,Suministro de dos cabinas de seguridad biológi...,64049.62,64049.62,77500.04,None,None,20,[33190000],https://contrataciondelestado.es/wps/wcm/conne...,PLIEGO ABIERTO simplif SUMINISTROS_modificado ...,https://contrataciondelestado.es/wps/wcm/conne...,PPT PAS 668-24_firmado.pdf,None
16,EV,02/2025,"Contractació del servei de desinsectació, desr...",5373.2,5373.2,6501.57,2025-03-03,None,2,"[90922000, 90924000, 90921000, 90923000]",https://contrataciondelestado.es/FileSystem/se...,PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,PTRF.pdf,None
17,EV,23370/2024,Contrato de arrendamiento de inmueble propieda...,9187080,9187080,9554563.2,None,None,30,[70130000],https://contrataciondelestado.es/FileSystem/se...,1 PCAP PUERTA DE AFRICA FINAL.PDF,https://contrataciondelestado.es/FileSystem/se...,2 PPT PUERTA DE AFRICA FINAL.PDF,None
18,ADJ,2025-00756,Suministro de matricula 04225509 - kit para mo...,10956.5,9941.25,12028.91,None,None,12,[34312000],None,None,None,None,None
19,PUB,2121888R,Servicios de conserjería y explotación del bar...,61440,12720,15391.2,None,None,2,[98341130],https://contrataciondelestado.es/FileSystem/se...,PCAP.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT.pdf,None

,estado,expediente,objeto,valor_estimado,presupuesto_sin_iva,presupuesto_con_iva,plazo_inicio,plazo_fin,plazo_duracion,cpv_list,pliego_tecnico_uri,pliego_tecnico_id,pliego_admin_uri,pliego_admin_id,ted_uuid
32,PUB,4873/2024,Contrato de servicio de redacción del proyecto...,12892.8,12892.8,15600.29,None,None,60,"[71300000, 71323200, 71242000, 71520000, 71000...",https://contrataciondelestado.es/FileSystem/se...,PCAP CELESTINO.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT SANEAMIENTO RVDO CELESTINO NAVARRO BLESA.pdf,None
222,ADJ,2025-00786,Suministro de camiseta y pantalon termico_au118,21.89,21.89,26.49,None,None,12,[18113000],None,None,None,None,None
90,ADJ,OC-7579/24,Arrendamiento de un piso en Alzira para el pro...,15600,7800,7800,None,None,12,[70310000],https://contrataciondelestado.es/FileSystem/se...,PLIEGO ADMINISTRATIVO.pdf,https://contrataciondelestado.es/FileSystem/se...,documento caracteristicas tecnicas.pdf,None
85,ADJ,SUM/DGA/10-2024,Pantalla Led exterior de gran formato a instal...,36300,36300,38841,None,None,5,[30231300],https://contrataciondelestado.es/wps/wcm/conne...,8_PCAP fdo.pdf,https://contrataciondelestado.es/wps/wcm/conne...,6_PPT_PantallaLed_Los_Llanos_V2.pdf,None
213,RES,4/2024 Villar del Rey,Concesión de servicios de la Estación de la De...,1074981.19,0,0,None,None,15,"[90481000, 90420000, 45259100, 45252130]",https://contrataciondelestado.es/FileSystem/se...,1482737-PliegodeClusulasAdmin-001001PCA_STD_OE...,https://contrataciondelestado.es/FileSystem/se...,1482729-PliegodePrescripcione-001001PPT_STD_OE...,None
105,PUB,32/2025 Cordobilla de Lácara,Obra e instalación incluyendo la puesta en mar...,43393,43393,52505.53,None,None,2,"[45317000, 45300000, 45311100, 45311000, 45311...",https://contrataciondelestado.es/FileSystem/se...,1613303--M2PLIEGOADMINISTRATIVOFOTOVOLTAICAmod...,https://contrataciondelestado.es/FileSystem/se...,1613295-PliegodePr-M2PLIEGOTECNICOFOTOVOLTAICA...,None
254,PUB,2024/15 Suministro Uniformidad Policia Local,"Suministro de prendas, útiles y complementos d...",16528.93,16528.93,20000,None,None,2,[35200000],https://contrataciondelestado.es/FileSystem/se...,PCAP suministro Uniformidad Policia Local.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT Suministro Uniformidad Policia Local.pdf,None
41,RES,2024/CONT0002,Suministro de tres vehículos adscritos al parq...,245540,202540,245540,None,None,120,[34130000],https://contrataciondelestado.es/wps/wcm/conne...,CONT0002 - PCAP VEHICULOS PARQUE MOVIL.pdf,https://contrataciondelestado.es/wps/wcm/conne...,CONT0002 - PPT VEHICULOS POR LOTES.pdf,None
34,RES,81/2024,Concesión administrativa del aprovechamiento c...,31688,31688,31688,2024-04-01,2026-03-31,None,"[03300000, 03000000]",None,None,None,None,None
83,ADJ,300/2024/00045-133,Suministro de 1.000 actas de inspección de con...,115,115,139.15,None,None,5,[22900000],https://contrataciondelestado.es/FileSystem/se...,23259409--InformePropuestaAdjudicacion133pdf_f...,https://contrataciondelestado.es/FileSystem/se...,23216464-ArteFinal-ArteFinalDefinitivo.pdf,None

In [88]:
PROCEDURE_CODE_MAP = {
    "1": "Abierto",
    "2": "Restringido",
    "3": "Negociado sin publicidad",
    "4": "Negociado con publicidad",
    "5": "Diálogo competitivo",
    "6": "Contrato Menor",
    "7": "Derivado de acuerdo marco",
    "8": "Concurso de proyectos",
    "100": "Normas internas",
    "999": "Otros",
}

URGENCY_CODE_MAP = {
    "1": "Ordinaria",
    "2": "Urgente",
    "3": "Emergencia",
}

In [91]:
from datetime import datetime

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_first_text(elem, path):
    cur = elem
    for name in path:
        found = None
        for ch in list(cur):
            if localname(ch.tag) == name:
                found = ch
                break
        if found is None:
            return None
        cur = found
    return (cur.text or "").strip()

def combine_date_time(date_str, time_str):
    if not date_str and not time_str:
        return None
    if date_str and time_str:
        return pd.to_datetime(f"{date_str} {time_str}", errors="coerce")
    if date_str:
        return pd.to_datetime(date_str, errors="coerce")
    return None

def extract_lotes(contract_folder_status):
    lotes = []
    for ch in list(contract_folder_status):
        if localname(ch.tag) == "ProcurementProjectLot":
            lote_id = find_first_text(ch, ["ID"])
            lote_obj = find_first_text(ch, ["ProcurementProject", "Name"])
            if lote_id or lote_obj:
                lotes.append((lote_id, lote_obj))
    return lotes

In [92]:
def extract_fields_preview(entry):
    cfs = None
    for ch in list(entry):
        if localname(ch.tag) == "ContractFolderStatus":
            cfs = ch
            break
    if cfs is None:
        return {}

    proc_code = find_first_text(cfs, ["TenderingProcess", "ProcedureCode"])
    urg_code = find_first_text(cfs, ["TenderingProcess", "UrgencyCode"])

    fecha = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndDate"])
    hora  = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndTime"])

    return {
        "id": find_first_text(entry, ["id"]),
        "procedimiento": PROCEDURE_CODE_MAP.get(proc_code, proc_code),
        "tramitacion": URGENCY_CODE_MAP.get(urg_code, urg_code),
        "plazo_presentacion": combine_date_time(fecha, hora),
        "lotes": extract_lotes(cfs),
        "resultado": find_first_text(cfs, ["TenderResult", "ResultCode"]),
        "ofertas_recibidas": find_first_text(cfs, ["TenderResult", "ReceivedTenderQuantity"]),
        "adjudicatario": find_first_text(cfs, ["TenderResult", "WinningParty", "PartyName", "Name"]),
        "importe_sin_iva": find_first_text(cfs, ["TenderResult", "AwardedTenderedProject", "LegalMonetaryTotal", "TaxExclusiveAmount"]),
        "importe_con_iva": find_first_text(cfs, ["TenderResult", "AwardedTenderedProject", "LegalMonetaryTotal", "PayableAmount"]),
    }

In [96]:
def extract_tender_results(cfs):
    results = []

    for tr in list(cfs):
        if localname(tr.tag) != "TenderResult":
            continue

        id_lote = find_first_text(tr, ["AwardedTenderedProject", "ProcurementProjectLotID"])

        row = {
            "idlote": id_lote,
            "resultado": find_first_text(tr, ["ResultCode"]),
            "fecha_acuerdo": find_first_text(tr, ["AwardDate"]),
            "ofertas_recibidas": find_first_text(tr, ["ReceivedTenderQuantity"]),
            "ofertas_pymes": find_first_text(tr, ["SMEsReceivedTenderQuantity"]),
            "adjudicatario_nombre": find_first_text(tr, ["WinningParty", "PartyName", "Name"]),
            "adjudicatario_id_tipo": find_first_attr(tr, ["WinningParty", "PartyIdentification", "ID"], "schemeName"),
            "adjudicatario_id": find_first_text(tr, ["WinningParty", "PartyIdentification", "ID"]),
            "adjudicatario_pyme": find_first_text(tr, ["SMEAwardedIndicator"]),
            "adjudicatario_ute": find_first_text(tr, ["WinningParty", "PartyLegalEntity", "CompanyTypeCode"]),
            "importe_total_sin_iva": find_first_text(tr, ["AwardedTenderedProject", "LegalMonetaryTotal", "TaxExclusiveAmount"]),
            "importe_total_con_iva": find_first_text(tr, ["AwardedTenderedProject", "LegalMonetaryTotal", "PayableAmount"]),
        }
        results.append(row)

    # --- normalización: escalar vs lista de (idlote, valor)
    out = {}
    fields = [k for k in results[0].keys() if k != "idlote"] if results else []

    for field in fields:
        pairs = [(r["idlote"], r[field]) for r in results]

        # si no hay lote (todos None) y solo un elemento → escalar
        if len(pairs) == 1 and pairs[0][0] is None:
            out[field] = pairs[0][1]
        else:
            out[field] = pairs

    return out

In [98]:
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
from pathlib import Path

BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_path = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))[0]
MAX_ENTRIES = 20  # ajusta (10, 50, 200...)

PROCEDURE_CODE_MAP = {
    "1": "Abierto",
    "2": "Restringido",
    "3": "Negociado sin publicidad",
    "4": "Negociado con publicidad",
    "5": "Diálogo competitivo",
    "6": "Contrato menor",
    "7": "Derivado de acuerdo marco",
    "8": "Concurso de proyectos",
    "100": "Normas internas",
    "999": "Otros",
}
URGENCY_CODE_MAP = {"1": "Ordinaria", "2": "Urgente", "3": "Emergencia"}

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_child_by_localname(elem, name):
    for ch in list(elem):
        if localname(ch.tag) == name:
            return ch
    return None

def find_first_text(elem, path):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return (cur.text or "").strip()

def find_first_attr(elem, path, attr_name):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return cur.attrib.get(attr_name)

def combine_date_time(date_str, time_str):
    if not date_str and not time_str:
        return None
    if date_str and time_str:
        return pd.to_datetime(f"{date_str} {time_str}", errors="coerce")
    if date_str:
        return pd.to_datetime(date_str, errors="coerce")
    return None

def extract_lotes(cfs):
    lotes = []
    for ch in list(cfs):
        if localname(ch.tag) == "ProcurementProjectLot":
            lote_id = find_first_text(ch, ["ID"])
            lote_obj = find_first_text(ch, ["ProcurementProject", "Name"])
            if lote_id or lote_obj:
                lotes.append((lote_id, lote_obj))
    return lotes

def extract_23_fields(entry):
    cfs = find_child_by_localname(entry, "ContractFolderStatus")
    if cfs is None:
        return {}

    proc_code = find_first_text(cfs, ["TenderingProcess", "ProcedureCode"])
    urg_code  = find_first_text(cfs, ["TenderingProcess", "UrgencyCode"])

    end_date = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndDate"])
    end_time = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndTime"])
    plazo_presentacion = combine_date_time(end_date, end_time)

    # --- bloque TenderResult (con soporte de lotes) ---
    tr_block = extract_tender_results(cfs)  # <- ESTO VA FUERA DEL return

    base = {
        "id": find_first_text(entry, ["id"]),

        # Localización
        "subentidad_nacional": find_first_text(
            cfs, ["ProcurementProject", "RealizedLocation", "CountrySubentity"]
        ),
        "codigo_subentidad_territorial": find_first_text(
            cfs, ["ProcurementProject", "RealizedLocation", "CountrySubentityCode"]
        ),

        # Lotes de proyecto
        "lotes": extract_lotes(cfs),

        # Procedimiento / tramitación
        "tipo_procedimiento": PROCEDURE_CODE_MAP.get(proc_code, proc_code),
        "tramitacion": URGENCY_CODE_MAP.get(urg_code, urg_code),

        # Umbral
        "over_threshold": find_first_text(cfs, ["TenderingProcess", "OverThresholdIndicator"]),

        # Órgano de contratación
        "organo_nombre": find_first_text(cfs, ["LocatedContractingParty", "Party", "PartyName", "Name"]),
        "organo_id": find_first_text(cfs, ["LocatedContractingParty", "Party", "PartyIdentification", "ID"]),

        # Plazo presentación (datetime único)
        "plazo_presentacion": plazo_presentacion,
    }

    # fusionamos base + campos de TenderResult (resultado, importes, adjudicatario, etc.)
    return {**base, **tr_block}

# --- leer SOLO un atom y parar en MAX_ENTRIES ---
rows = []
with zipfile.ZipFile(zip_path, "r") as z:
    atoms = [n for n in z.namelist() if n.lower().endswith(".atom")]
    atom_name = atoms[0]

    with z.open(atom_name) as f:
        root = ET.parse(f).getroot()

    for entry in list(root):
        if localname(entry.tag) != "entry":
            continue
        rows.append(extract_23_fields(entry))
        if len(rows) >= MAX_ENTRIES:
            break

df_preview_23 = pd.DataFrame(rows)

# Muestra general
display(df_preview_23.head(10))

# Muestra "interesante": donde haya adjudicatario/resultado
display(df_preview_23[df_preview_23["resultado"].notna()].head(10))

# Muestra "interesante": donde haya >1 lote
display(df_preview_23[df_preview_23["lotes"].apply(lambda x: isinstance(x, list) and len(x) > 1)].head(10))

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,...,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,adjudicatario_id_tipo,adjudicatario_id,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
0,https://contrataciondelestado.es/sindicacion/l...,A Coruña,ES111,[],9,Ordinaria,false,Alcaldía del Concello de Fene,L01150354,2024-11-14 23:59:00,...,2025-02-20,12,12,"EXCAVACIONES Y OBRAS CANDAL, S.L.",NIF,B15496219,true,None,68780.44,83224.33
1,https://contrataciondelestado.es/sindicacion/l...,Murcia,ES620,"[(1, Aula de naturaleza, centro de visitantes ...",Abierto,Ordinaria,true,Junta de Gobierno del Ayuntamiento de Murcia,L01300308,2025-02-24 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,[],9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,[],9,Ordinaria,false,Departamento de Salud de Orihuela. Dirección E...,S4611001A,2025-02-11 14:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Rectorado de la Universidad de Córdoba,U00600001,2024-02-20 17:00:00,...,2024-04-18,2,1,"TAI SOFTWARE SOLUTIONS IBERIA, S.L.",NIF,B88446885,true,None,33000,39930
5,https://contrataciondelestado.es/sindicacion/l...,Melilla,ES640,[],9,Ordinaria,false,Consejería de Hacienda de la Ciudad Autónoma d...,S7900010E,2025-03-10 15:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Alcaldía del Ayuntamiento de Baena,L01140076,2025-03-25 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,[],Abierto,Urgente,false,Alcaldía del Ayuntamiento de Beas de Segura,L01230124,2025-02-19 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, 2 cabinas de seguridad biológica para el ...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://contrataciondelestado.es/sindicacion/l...,Menorca,ES533,[],9,Ordinaria,false,Patronat de Fundació per a Persones amb Discap...,G57505885,2025-02-21 15:00:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,...,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,adjudicatario_id_tipo,adjudicatario_id,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
0,https://contrataciondelestado.es/sindicacion/l...,A Coruña,ES111,[],9,Ordinaria,false,Alcaldía del Concello de Fene,L01150354,2024-11-14 23:59:00,...,2025-02-20,12,12,"EXCAVACIONES Y OBRAS CANDAL, S.L.",NIF,B15496219,true,None,68780.44,83224.33
4,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Rectorado de la Universidad de Córdoba,U00600001,2024-02-20 17:00:00,...,2024-04-18,2,1,"TAI SOFTWARE SOLUTIONS IBERIA, S.L.",NIF,B88446885,true,None,33000,39930
11,https://contrataciondelestado.es/sindicacion/l...,ESPAÑA,ES,[],Normas internas,Ordinaria,false,Dirección General de Renfe Ingeniería y Manten...,EA0008560,NaT,...,2025-02-27,1,0,TECOMAR S.L.,NIF,B20071155,false,None,9941.25,12028.91
16,https://contrataciondelestado.es/sindicacion/l...,Valencia/València,ES523,[],9,Ordinaria,false,Presidencia de la Mancomunidad del Interior Ti...,L05460018,2025-02-14 23:59:00,...,2025-02-26,4,4,"Vetocu, S.L.",NIF,B42928200,false,None,22500,27225
17,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,"[(1, Calle Niña Ana), (2, Calle Goya), (3, Cal...",Abierto,Ordinaria,false,Alcaldia del Ayuntamiento de Quesada,L01230737,2025-02-10 23:59:00,...,"[(1, 2025-02-24), (2, 2025-02-27), (3, 2025-02...","[(1, 5), (2, 5), (3, 5), (4, 5)]","[(1, 0), (2, 2), (3, 2), (4, 0)]","[(1, JUAN ANTONIO PLAZA RAMOS), (2, SERVICIOS ...","[(1, NIF), (2, NIF), (3, NIF), (4, NIF)]","[(1, 26459418B), (2, B23741911), (3, B23741911...","[(1, false), (2, true), (3, true), (4, false)]","[(1, None), (2, None), (3, None), (4, None)]","[(1, 7930), (2, 11450), (3, 14800), (4, 6990)]","[(1, 9595.3), (2, 13854.5), (3, 17908), (4, 84..."
18,https://contrataciondelestado.es/sindicacion/l...,Región de Murcia,ES62,[],9,Ordinaria,false,"Empresa de Transformación Agraria S.A.,S.M.E.,...",A28476208,2025-01-14 14:00:00,...,2025-02-26,5,4,"INNOVACIÓN GLOBAL DE SEGURIDAD,S.A.",NIF,A86376803,true,None,53279.72,64468.46

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,...,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,adjudicatario_id_tipo,adjudicatario_id,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
1,https://contrataciondelestado.es/sindicacion/l...,Murcia,ES620,"[(1, Aula de naturaleza, centro de visitantes ...",Abierto,Ordinaria,true,Junta de Gobierno del Ayuntamiento de Murcia,L01300308,2025-02-24 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, 2 cabinas de seguridad biológica para el ...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,"[(1, Calle Niña Ana), (2, Calle Goya), (3, Cal...",Abierto,Ordinaria,false,Alcaldia del Ayuntamiento de Quesada,L01230737,2025-02-10 23:59:00,...,"[(1, 2025-02-24), (2, 2025-02-27), (3, 2025-02...","[(1, 5), (2, 5), (3, 5), (4, 5)]","[(1, 0), (2, 2), (3, 2), (4, 0)]","[(1, JUAN ANTONIO PLAZA RAMOS), (2, SERVICIOS ...","[(1, NIF), (2, NIF), (3, NIF), (4, NIF)]","[(1, 26459418B), (2, B23741911), (3, B23741911...","[(1, false), (2, true), (3, true), (4, false)]","[(1, None), (2, None), (3, None), (4, None)]","[(1, 7930), (2, 11450), (3, 14800), (4, 6990)]","[(1, 9595.3), (2, 13854.5), (3, 17908), (4, 84..."
19,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, Lote 1. Dos monitores transcutáneo de CO2...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-08 23:59:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
import zipfile
import xml.etree.ElementTree as ET
import pandas as pd
from pathlib import Path

# ---------- Config ----------
BASE = Path("/home/jarenas/Datasets/PLACE/2025")
zip_path = sorted(BASE.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))[0]
MAX_ENTRIES = 50  # ajusta: 10, 50, 200...

PROCEDURE_CODE_MAP = {
    "1": "Abierto",
    "2": "Restringido",
    "3": "Negociado sin publicidad",
    "4": "Negociado con publicidad",
    "5": "Diálogo competitivo",
    "6": "Contrato menor",
    "7": "Derivado de acuerdo marco",
    "8": "Concurso de proyectos",
    "100": "Normas internas",
    "999": "Otros",
}
URGENCY_CODE_MAP = {"1": "Ordinaria", "2": "Urgente", "3": "Emergencia"}

# ---------- Helpers XML ----------
def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_child_by_localname(elem, name):
    for ch in list(elem):
        if localname(ch.tag) == name:
            return ch
    return None

def find_children_by_localname(elem, name):
    return [ch for ch in list(elem) if localname(ch.tag) == name]

def find_first_text(elem, path):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return (cur.text or "").strip()

def find_first_attr(elem, path, attr_name):
    cur = elem
    for name in path:
        cur = find_child_by_localname(cur, name)
        if cur is None:
            return None
    return cur.attrib.get(attr_name)

def combine_date_time(date_str, time_str):
    if not date_str and not time_str:
        return None
    if date_str and time_str:
        return pd.to_datetime(f"{date_str} {time_str}", errors="coerce")
    if date_str:
        return pd.to_datetime(date_str, errors="coerce")
    return None

# ---------- Lotes ----------
def extract_lotes(cfs):
    lotes = []
    for lot in find_children_by_localname(cfs, "ProcurementProjectLot"):
        lote_id = find_first_text(lot, ["ID"])
        lote_obj = find_first_text(lot, ["ProcurementProject", "Name"])
        if lote_id or lote_obj:
            lotes.append((lote_id, lote_obj))
    return lotes

# ---------- TenderResult (con normalización de identificador) ----------
def extract_tender_results(cfs):
    results = []
    for tr in find_children_by_localname(cfs, "TenderResult"):
        id_lote = find_first_text(tr, ["AwardedTenderedProject", "ProcurementProjectLotID"])
        id_tipo = find_first_attr(tr, ["WinningParty", "PartyIdentification", "ID"], "schemeName")
        id_val  = find_first_text(tr, ["WinningParty", "PartyIdentification", "ID"])

        results.append({
            "idlote": id_lote,
            "resultado": find_first_text(tr, ["ResultCode"]),
            "fecha_acuerdo": find_first_text(tr, ["AwardDate"]),
            "ofertas_recibidas": find_first_text(tr, ["ReceivedTenderQuantity"]),
            "ofertas_pymes": find_first_text(tr, ["SMEsReceivedTenderQuantity"]),
            "adjudicatario_nombre": find_first_text(tr, ["WinningParty", "PartyName", "Name"]),
            "identificador": (id_tipo, id_val),  # (tipo, id)
            "adjudicatario_pyme": find_first_text(tr, ["SMEAwardedIndicator"]),
            "adjudicatario_ute": find_first_text(tr, ["WinningParty", "PartyLegalEntity", "CompanyTypeCode"]),
            "importe_total_sin_iva": find_first_text(tr, ["AwardedTenderedProject", "LegalMonetaryTotal", "TaxExclusiveAmount"]),
            "importe_total_con_iva": find_first_text(tr, ["AwardedTenderedProject", "LegalMonetaryTotal", "PayableAmount"]),
        })

    if not results:
        return {}

    out = {}
    fields = [k for k in results[0].keys() if k != "idlote"]

    for field in fields:
        values = []
        for r in results:
            if r["idlote"] is None:
                values.append(r[field])
            else:
                if field == "identificador":
                    tipo, val = r[field]
                    values.append((r["idlote"], tipo, val))
                else:
                    values.append((r["idlote"], r[field]))

        if len(results) == 1 and results[0]["idlote"] is None:
            out[field] = values[0]
        else:
            out[field] = values

    return out

# ---------- Extractor 23 campos + bloques ----------
def extract_preview_fields(entry):
    cfs = find_child_by_localname(entry, "ContractFolderStatus")
    if cfs is None:
        return {}

    proc_code = find_first_text(cfs, ["TenderingProcess", "ProcedureCode"])
    urg_code  = find_first_text(cfs, ["TenderingProcess", "UrgencyCode"])

    end_date = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndDate"])
    end_time = find_first_text(cfs, ["TenderingProcess", "TenderSubmissionDeadlinePeriod", "EndTime"])
    plazo_presentacion = combine_date_time(end_date, end_time)

    base = {
        "id": find_first_text(entry, ["id"]),
        "subentidad_nacional": find_first_text(cfs, ["ProcurementProject", "RealizedLocation", "CountrySubentity"]),
        "codigo_subentidad_territorial": find_first_text(cfs, ["ProcurementProject", "RealizedLocation", "CountrySubentityCode"]),
        "lotes": extract_lotes(cfs),
        "tipo_procedimiento": PROCEDURE_CODE_MAP.get(proc_code, proc_code),
        "tramitacion": URGENCY_CODE_MAP.get(urg_code, urg_code),
        "over_threshold": find_first_text(cfs, ["TenderingProcess", "OverThresholdIndicator"]),
        "organo_nombre": find_first_text(cfs, ["LocatedContractingParty", "Party", "PartyName", "Name"]),
        "organo_id": find_first_text(cfs, ["LocatedContractingParty", "Party", "PartyIdentification", "ID"]),
        "plazo_presentacion": plazo_presentacion,
    }

    tr_block = extract_tender_results(cfs)
    return {**base, **tr_block}

# ---------- Leer SOLO un atom y mostrar previews ----------
rows = []
with zipfile.ZipFile(zip_path, "r") as z:
    atoms = [n for n in z.namelist() if n.lower().endswith(".atom")]
    atom_name = atoms[0]

    with z.open(atom_name) as f:
        root = ET.parse(f).getroot()

    for entry in list(root):
        if localname(entry.tag) != "entry":
            continue
        rows.append(extract_preview_fields(entry))
        if len(rows) >= MAX_ENTRIES:
            break

df_preview = pd.DataFrame(rows)

display(df_preview.head(10))
display(df_preview[df_preview.get("resultado").notna()].head(10))
display(df_preview[df_preview["lotes"].apply(lambda x: isinstance(x, list) and len(x) > 1)].head(10))

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,resultado,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,identificador,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
0,https://contrataciondelestado.es/sindicacion/l...,A Coruña,ES111,[],9,Ordinaria,false,Alcaldía del Concello de Fene,L01150354,2024-11-14 23:59:00,8,2025-02-20,12,12,"EXCAVACIONES Y OBRAS CANDAL, S.L.","(NIF, B15496219)",true,None,68780.44,83224.33
1,https://contrataciondelestado.es/sindicacion/l...,Murcia,ES620,"[(1, Aula de naturaleza, centro de visitantes ...",Abierto,Ordinaria,true,Junta de Gobierno del Ayuntamiento de Murcia,L01300308,2025-02-24 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,[],9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,[],9,Ordinaria,false,Departamento de Salud de Orihuela. Dirección E...,S4611001A,2025-02-11 14:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Rectorado de la Universidad de Córdoba,U00600001,2024-02-20 17:00:00,8,2024-04-18,2,1,"TAI SOFTWARE SOLUTIONS IBERIA, S.L.","(NIF, B88446885)",true,None,33000,39930
5,https://contrataciondelestado.es/sindicacion/l...,Melilla,ES640,[],9,Ordinaria,false,Consejería de Hacienda de la Ciudad Autónoma d...,S7900010E,2025-03-10 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Alcaldía del Ayuntamiento de Baena,L01140076,2025-03-25 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,[],Abierto,Urgente,false,Alcaldía del Ayuntamiento de Beas de Segura,L01230124,2025-02-19 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, 2 cabinas de seguridad biológica para el ...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,https://contrataciondelestado.es/sindicacion/l...,Menorca,ES533,[],9,Ordinaria,false,Patronat de Fundació per a Persones amb Discap...,G57505885,2025-02-21 15:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,resultado,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,identificador,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
0,https://contrataciondelestado.es/sindicacion/l...,A Coruña,ES111,[],9,Ordinaria,false,Alcaldía del Concello de Fene,L01150354,2024-11-14 23:59:00,8,2025-02-20,12,12,"EXCAVACIONES Y OBRAS CANDAL, S.L.","(NIF, B15496219)",true,None,68780.44,83224.33
4,https://contrataciondelestado.es/sindicacion/l...,Córdoba,ES613,[],9,Ordinaria,false,Rectorado de la Universidad de Córdoba,U00600001,2024-02-20 17:00:00,8,2024-04-18,2,1,"TAI SOFTWARE SOLUTIONS IBERIA, S.L.","(NIF, B88446885)",true,None,33000,39930
11,https://contrataciondelestado.es/sindicacion/l...,ESPAÑA,ES,[],Normas internas,Ordinaria,false,Dirección General de Renfe Ingeniería y Manten...,EA0008560,NaT,8,2025-02-27,1,0,TECOMAR S.L.,"(NIF, B20071155)",false,None,9941.25,12028.91
16,https://contrataciondelestado.es/sindicacion/l...,Valencia/València,ES523,[],9,Ordinaria,false,Presidencia de la Mancomunidad del Interior Ti...,L05460018,2025-02-14 23:59:00,9,2025-02-26,4,4,"Vetocu, S.L.","(NIF, B42928200)",false,None,22500,27225
17,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,"[(1, Calle Niña Ana), (2, Calle Goya), (3, Cal...",Abierto,Ordinaria,false,Alcaldia del Ayuntamiento de Quesada,L01230737,2025-02-10 23:59:00,"[(1, 9), (2, 8), (3, 8), (4, 9)]","[(1, 2025-02-24), (2, 2025-02-27), (3, 2025-02...","[(1, 5), (2, 5), (3, 5), (4, 5)]","[(1, 0), (2, 2), (3, 2), (4, 0)]","[(1, JUAN ANTONIO PLAZA RAMOS), (2, SERVICIOS ...","[(1, NIF, 26459418B), (2, NIF, B23741911), (3,...","[(1, false), (2, true), (3, true), (4, false)]","[(1, None), (2, None), (3, None), (4, None)]","[(1, 7930), (2, 11450), (3, 14800), (4, 6990)]","[(1, 9595.3), (2, 13854.5), (3, 17908), (4, 84..."
18,https://contrataciondelestado.es/sindicacion/l...,Región de Murcia,ES62,[],9,Ordinaria,false,"Empresa de Transformación Agraria S.A.,S.M.E.,...",A28476208,2025-01-14 14:00:00,8,2025-02-26,5,4,"INNOVACIÓN GLOBAL DE SEGURIDAD,S.A.","(NIF, A86376803)",true,None,53279.72,64468.46
22,https://contrataciondelestado.es/sindicacion/l...,None,ES618,[],9,Ordinaria,false,Alcaldía del Ayuntamiento de Castilleja de la ...,L01410299,2025-02-21 23:59:00,9,2025-02-26,1,1,TALLERES Y GRUAS CASTILLEJA S.L.,"(NIF, B91131748)",true,None,30939.47,37436.76
24,https://contrataciondelestado.es/sindicacion/l...,Valencia/València,ES523,"[(1, Control y prevención de la legionella), (...",9,Ordinaria,false,Junta de Gobierno del Ayuntamiento de Alboraya,L01460137,2024-12-12 23:59:00,"[(1, 8), (2, 8)]","[(1, 2025-02-25), (2, 2025-02-25)]","[(1, 5), (2, 5)]","[(1, 4), (2, 5)]","[(1, BELTIS INTEGRAL, SL), (2, Analiza Control...","[(1, NIF, B54500202), (2, NIF, B09394107)]","[(1, true), (2, true)]","[(1, None), (2, None)]","[(1, 57421.29), (2, 17496)]","[(1, 69480.13), (2, 21170.16)]"
26,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,[],Abierto,Urgente,true,Alcaldia del Ayuntamiento de Rafal,L01031091,2018-10-29 23:59:00,9,2019-01-04,4,4,"Tetma - Vivers Centre Verd, s.a.","(NIF, A96072087)",false,None,0,0
27,https://contrataciondelestado.es/sindicacion/l...,Zamora,ES419,[],9,Urgente,false,Alcaldía del Ayuntamiento de Requejo,L01491743,2024-04-08 23:59:00,9,2024-04-22,2,1,JMB ACTIVIDADES CINEGÉTICAS Y EVENTOS S.L.,"(OTROS, B84859354)",false,None,23101,23101

,id,subentidad_nacional,codigo_subentidad_territorial,lotes,tipo_procedimiento,tramitacion,over_threshold,organo_nombre,organo_id,plazo_presentacion,resultado,fecha_acuerdo,ofertas_recibidas,ofertas_pymes,adjudicatario_nombre,identificador,adjudicatario_pyme,adjudicatario_ute,importe_total_sin_iva,importe_total_con_iva
1,https://contrataciondelestado.es/sindicacion/l...,Murcia,ES620,"[(1, Aula de naturaleza, centro de visitantes ...",Abierto,Ordinaria,true,Junta de Gobierno del Ayuntamiento de Murcia,L01300308,2025-02-24 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, 2 cabinas de seguridad biológica para el ...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-10 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,https://contrataciondelestado.es/sindicacion/l...,Jaén,ES616,"[(1, Calle Niña Ana), (2, Calle Goya), (3, Cal...",Abierto,Ordinaria,false,Alcaldia del Ayuntamiento de Quesada,L01230737,2025-02-10 23:59:00,"[(1, 9), (2, 8), (3, 8), (4, 9)]","[(1, 2025-02-24), (2, 2025-02-27), (3, 2025-02...","[(1, 5), (2, 5), (3, 5), (4, 5)]","[(1, 0), (2, 2), (3, 2), (4, 0)]","[(1, JUAN ANTONIO PLAZA RAMOS), (2, SERVICIOS ...","[(1, NIF, 26459418B), (2, NIF, B23741911), (3,...","[(1, false), (2, true), (3, true), (4, false)]","[(1, None), (2, None), (3, None), (4, None)]","[(1, 7930), (2, 11450), (3, 14800), (4, 6990)]","[(1, 9595.3), (2, 13854.5), (3, 17908), (4, 84..."
19,https://contrataciondelestado.es/sindicacion/l...,Alicante/Alacant,ES521,"[(1, Lote 1. Dos monitores transcutáneo de CO2...",9,Ordinaria,false,Departamento de Salud Alicante. Dirección Econ...,S4611001A,2025-01-08 23:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,https://contrataciondelestado.es/sindicacion/l...,Málaga,ES617,"[(1, Lote 1: Servicio de diseño gráfico del ma...",Abierto,Ordinaria,false,Junta de Gobierno del Ayuntamiento de Málaga,L01290672,2024-12-02 13:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,https://contrataciondelestado.es/sindicacion/l...,Valencia/València,ES523,"[(1, Control y prevención de la legionella), (...",9,Ordinaria,false,Junta de Gobierno del Ayuntamiento de Alboraya,L01460137,2024-12-12 23:59:00,"[(1, 8), (2, 8)]","[(1, 2025-02-25), (2, 2025-02-25)]","[(1, 5), (2, 5)]","[(1, 4), (2, 5)]","[(1, BELTIS INTEGRAL, SL), (2, Analiza Control...","[(1, NIF, B54500202), (2, NIF, B09394107)]","[(1, true), (2, true)]","[(1, None), (2, None)]","[(1, 57421.29), (2, 17496)]","[(1, 69480.13), (2, 21170.16)]"
29,https://contrataciondelestado.es/sindicacion/l...,Zaragoza,ES243,"[(1, Mobiliario de oficina), (2, Sillería de o...",Abierto,Ordinaria,true,Gobierno de Zaragoza,L01502973,2025-01-20 12:59:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,https://contrataciondelestado.es/sindicacion/l...,Canarias,ES70,"[(1, Creación y producción), (2, Planes de med...",Abierto,Ordinaria,true,Dirección General de Salud Pública del Gobiern...,A05003613,2025-03-31 12:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,https://contrataciondelestado.es/sindicacion/l...,Málaga,ES617,"[(1, Lote 1: Vehículo del tipo camión con pla...",9,Ordinaria,true,Presidencia de la Mancomunidad de Municipios d...,L05290002,2024-06-04 15:00:00,"[(1, 9), (2, 9), (3, 3)]","[(1, 2024-07-31), (2, 2024-07-31), (3, 2024-07...","[(1, 4), (2, 3), (3, 0)]","[(1, 4), (2, 3), (3, 0)]","[(1, GUILLERMO GARCIA MUÑOZ, S.L.), (2, GUILLE...","[(1, NIF, B23046840), (2, NIF, B23046840), (3,...","[(1, true), (2, true), (3, None)]","[(1, None), (2, None), (3, None)]","[(1, 74400), (2, 105000), (3, None)]","[(1, 90024), (2, 127050), (3, None)]"
36,https://contrataciondelestado.es/sindicacion/l...,Zaragoza,ES243,"[(1, FINCA REGISTRAL 12766. Urbana. Finca resu...",Abierto,Ordinaria,false,Pleno del Ayuntamiento de Calatorao,L01500687,2024-04-15 23:59:00,"[(1, 8), (2, 8), (3, 8), (4, 8), (5, 8)]","[(1, 2024-02-09), (2, 2024-02-09), (3, 2024-02...","[(1, 1), (2, 1), (3, 1), (4, 1), (5, 1)]","[(1, 0), (2, 0), (3, 0), (4, 0), (5, 0)]","[(1, CALANZA INMUEBLES, S.L.), (2, CALANZA INM...","[(1, NIF, B72506751), (2, NIF, B72506751), (3,...","[(1, false), (2, false), (3, false), (4, false...","[(1, None), (2, None), (3, None), (4, None), (...","[(1, 50000), (2, 189000), (3, 118000), (4, 280...","[(1, 51000), (2, 192780), (3, 120360), (4, 285..."

In [49]:
# Inspecciona un entry que haya salido todo NaN
from pprint import pprint

def debug_first_empty_entry(base_dir):
    base = Path(base_dir)
    zp = sorted(base.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))[0]
    with zipfile.ZipFile(zp, "r") as z:
        atom = [n for n in z.namelist() if n.lower().endswith(".atom")][0]
        with z.open(atom) as f:
            root = ET.parse(f).getroot()

        for entry in list(root):
            cfs = find_child_by_localname(entry, "ContractFolderStatus")
            if cfs is None:
                print("ENTRY SIN ContractFolderStatus:")
                print(ET.tostring(entry, encoding="unicode")[:1000])
                break

debug_first_empty_entry("/home/jarenas/Datasets/PLACE/2025")

ENTRY SIN ContractFolderStatus:
<ns0:author xmlns:ns0="http://www.w3.org/2005/Atom">
        <ns0:name>Plataforma de Contratación del Sector Público</ns0:name>
        <ns0:uri>https://contrataciondelestado.es</ns0:uri>
        <ns0:email>contrataciondelestado@hacienda.gob.es</ns0:email>
    </ns0:author>

In [50]:
import xml.etree.ElementTree as ET
from pathlib import Path
import zipfile
import pandas as pd

def localname(tag: str) -> str:
    return tag.split("}", 1)[1] if tag.startswith("{") else tag

def find_child_by_localname(elem, name):
    for ch in list(elem):
        if localname(ch.tag) == name:
            return ch
    return None

def extract_ted_uuid_and_id(entry):
    cfs = find_child_by_localname(entry, "ContractFolderStatus")
    if cfs is None:
        return None

    ted_uuid = None
    for ch in list(cfs):
        if localname(ch.tag) == "UUID" and ch.attrib.get("schemeName") == "TED":
            ted_uuid = (ch.text or "").strip()

    eid = None
    for ch in list(entry):
        if localname(ch.tag) == "id":
            eid = (ch.text or "").strip()

    return {
        "id": eid,
        "ted_uuid": ted_uuid
    }

def find_examples_with_ted_uuid(base_dir, max_examples=10, max_atoms=10):
    base = Path(base_dir)
    zip_files = sorted(base.glob("licitacionesPerfilesContratanteCompleto3_2025*.zip"))

    rows = []
    for zp in zip_files:
        with zipfile.ZipFile(zp, "r") as z:
            atoms = [n for n in z.namelist() if n.lower().endswith(".atom")]
            for atom in atoms[:max_atoms]:   # limita atoms para que sea rápido
                with z.open(atom) as f:
                    root = ET.parse(f).getroot()

                for entry in list(root):
                    rec = extract_ted_uuid_and_id(entry)
                    if rec and rec["ted_uuid"]:
                        rows.append(rec)
                        if len(rows) >= max_examples:
                            return pd.DataFrame(rows)

    return pd.DataFrame(rows)

df_ted = find_examples_with_ted_uuid(
    base_dir="/home/jarenas/Datasets/PLACE/2025",
    max_examples=10,
    max_atoms=20,   # puedes subir si salen pocos
)

display(df_ted)

,id,ted_uuid
0,https://contrataciondelestado.es/sindicacion/l...,b9110180-dd40-4b93-b183-6ae2dfb91718
1,https://contrataciondelestado.es/sindicacion/l...,934ad7bb-8ef8-4ef3-86d5-6e8837a3a3a9
2,https://contrataciondelestado.es/sindicacion/l...,70a34b75-a77c-4fe9-8427-edfe5d368ae2
3,https://contrataciondelestado.es/sindicacion/l...,bfed16dc-c66e-466e-96b8-e71ec65e8a73
4,https://contrataciondelestado.es/sindicacion/l...,3b674f3f-9527-4dd6-ba78-c51545bc1680
5,https://contrataciondelestado.es/sindicacion/l...,b36fb51a-62e4-4f87-8bd5-0361aa7a141d
6,https://contrataciondelestado.es/sindicacion/l...,0e312466-d0f0-401a-844e-ae93b9bd5dd0
7,https://contrataciondelestado.es/sindicacion/l...,4864dbb8-c12d-4ede-a2b5-89288c831a35
8,https://contrataciondelestado.es/sindicacion/l...,3dbfb8fe-c40a-4b53-b092-6bf9067b9da5
9,https://contrataciondelestado.es/sindicacion/l...,ef611a6f-622e-4d75-9c77-341c75698836

#### Verificación de ingesta

In [40]:
zip_glob = "/home/jarenas/Datasets/PLACE/2025/licitacionesPerfilesContratanteCompleto3_2025*.zip"

df_new = build_latest_entries(
    zip_glob,
    parquet_path=None,        # o "/home/jarenas/Datasets/PLACE/2025/atom_latest.parquet"
    show_progress=True,
    max_workers=16,           # prueba 12–16; si el disco sufre, baja a 8–12
)

Parsing .atom: 100%|█████████████████████████████████████████████████████████████████████████████| 1312/1312 [00:51<00:00, 25.27atom/s]

In [42]:
import pandas as pd

# Ajusta estos nombres si tus variables se llaman distinto
#df_new = df_latest  # <- dataframe generado por build_latest_entries
df_old = pd.read_parquet("/home/jarenas/Datasets/PLACE/2025/insiders_unificado.parquet", engine="fastparquet")

cols = ["id", "title", "summary", "updated", "link"]
cols2 = ["id", "objective", "summary", "updated", "link"]

# Asegurar tipos coherentes
df_new_cmp = df_new[cols].copy()
df_old_cmp = df_old[cols2].copy()

# Tomamos 10 ids al azar del nuevo DF (o los 10 primeros si prefieres)
sample_ids = df_new_cmp["id"].dropna().sample(10, random_state=42).tolist()

print("=== NUEVO DF (ingesta actual) ===")
display(df_new_cmp[df_new_cmp["id"].isin(sample_ids)].sort_values("id").reset_index(drop=True))

print("\n=== PARQUET UNIFICADO (existente) ===")
display(df_old_cmp[df_old_cmp["id"].isin(sample_ids)].sort_values("id").reset_index(drop=True))

=== NUEVO DF (ingesta actual) ===

,id,title,summary,updated,link
0,https://contrataciondelestado.es/sindicacion/l...,Trabajos de reparación varios y puesta en marc...,Id licitación: TSA0076562; Órgano de Contratac...,2025-09-10T12:04:04.612+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
1,https://contrataciondelestado.es/sindicacion/l...,Contrato de servicios de mantenimiento eléctri...,Id licitación: PC-MER/2024/00032-ORD; Órgano d...,2025-12-17T13:57:40.269+01:00,https://contrataciondelestado.es/wps/poc?uri=d...
2,https://contrataciondelestado.es/sindicacion/l...,Suministro de energía eléctrica en el edificio...,Id licitación: 2024/00706; Órgano de Contratac...,2025-06-20T08:05:05.905+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
3,https://contrataciondelestado.es/sindicacion/l...,"Uso común especial de espacios públicos, concr...",Id licitación: 72 2025; Órgano de Contratación...,2025-04-11T10:12:01.159+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
4,https://contrataciondelestado.es/sindicacion/l...,Prórroga segunda del contrato de servicio de i...,Id licitación: CPRORR/2025/ISTC0/0002; Órgano ...,2025-04-17T12:01:46.205+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
5,https://contrataciondelestado.es/sindicacion/l...,Procedimientos quirúrgicos del Acuerdo Marco ...,Id licitación: Z-118/2025; Órgano de Contratac...,2025-05-19T12:31:08.403+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
6,https://contrataciondelestado.es/sindicacion/l...,Servicio de limpieza de centros de la Direcció...,Id licitación: DGCPC-40/2025; Órgano de Contra...,2025-11-25T10:06:12.321+01:00,https://contrataciondelestado.es/wps/poc?uri=d...
7,https://contrataciondelestado.es/sindicacion/l...,Suministro lote 147 del Acuerdo Marco de medic...,Id licitación: 50/F/25/SU/GE/N/188_3; Órgano d...,2025-08-29T14:30:00.627+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
8,https://contrataciondelestado.es/sindicacion/l...,ORM 2018AR021S .- contrato basado en acuerdo m...,Id licitación: 2025/AR43U/00001530E; Órgano de...,2025-09-18T08:47:01.703+02:00,https://contrataciondelestado.es/wps/poc?uri=d...
9,https://contrataciondelestado.es/sindicacion/l...,Servicio de realización de procedimientos diag...,Id licitación: 0046/2025/2005; Órgano de Contr...,2025-11-18T09:49:36.658+01:00,https://contrataciondelestado.es/wps/poc?uri=d...

=== PARQUET UNIFICADO (existente) ===

,id,objective,summary,updated,link
0,https://contrataciondelestado.es/sindicacion/l...,Trabajos de reparación varios y puesta en marc...,Id licitación: TSA0076562; Órgano de Contratac...,2025-09-10 10:04:04.612000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
1,https://contrataciondelestado.es/sindicacion/l...,Contrato de servicios de mantenimiento eléctri...,Id licitación: PC-MER/2024/00032-ORD; Órgano d...,2025-12-17 12:57:40.269000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
2,https://contrataciondelestado.es/sindicacion/l...,Suministro de energía eléctrica en el edificio...,Id licitación: 2024/00706; Órgano de Contratac...,2025-06-20 06:05:05.905000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
3,https://contrataciondelestado.es/sindicacion/l...,"Uso común especial de espacios públicos, concr...",Id licitación: 72 2025; Órgano de Contratación...,2025-04-11 08:12:01.159000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
4,https://contrataciondelestado.es/sindicacion/l...,Prórroga segunda del contrato de servicio de i...,Id licitación: CPRORR/2025/ISTC0/0002; Órgano ...,2025-04-17 10:01:46.205000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
5,https://contrataciondelestado.es/sindicacion/l...,Procedimientos quirúrgicos del Acuerdo Marco ...,Id licitación: Z-118/2025; Órgano de Contratac...,2025-05-19 10:31:08.403000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
6,https://contrataciondelestado.es/sindicacion/l...,Servicio de limpieza de centros de la Direcció...,Id licitación: DGCPC-40/2025; Órgano de Contra...,2025-11-25 09:06:12.321000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
7,https://contrataciondelestado.es/sindicacion/l...,Suministro lote 147 del Acuerdo Marco de medic...,Id licitación: 50/F/25/SU/GE/N/188_3; Órgano d...,2025-08-29 12:30:00.627000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
8,https://contrataciondelestado.es/sindicacion/l...,ORM 2018AR021S .- contrato basado en acuerdo m...,Id licitación: 2025/AR43U/00001530E; Órgano de...,2025-09-18 06:47:01.703000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...
9,https://contrataciondelestado.es/sindicacion/l...,Servicio de realización de procedimientos diag...,Id licitación: 0046/2025/2005; Órgano de Contr...,2025-11-18 08:49:36.658000+00:00,https://contrataciondelestado.es/wps/poc?uri=d...

In [81]:
COL_MAP = {
    "id": "id",
    "updated": "updated",
    "title": "objective",
    "summary": "summary",
    "link": "link",

    "estado": "ContractFolderStatus_ContractFolderStatusCode",
    "expediente": "expedient",
    "objeto": "ContractFolderStatus_ProcurementProject_Name",

    "valor_estimado": "budget",
    "presupuesto_sin_iva": "ContractFolderStatus_ProcurementProject_BudgetAmount_TaxExclusiveAmount",
    "presupuesto_con_iva": "ContractFolderStatus_ProcurementProject_BudgetAmount_TotalAmount",

    "duracion_dias": "ContractFolderStatus_ProcurementProject_PlannedPeriod_DurationMeasure",

    "cpv_list": "cpv",

    "pliego_admin_URI": "url.administrativo",
    "pliego_admin_filename": "url.id_administrativo",

    "pliego_tecnico_URI": "url.tecnico",
    "pliego_tecnico_filename": "url.id_tecnico",

    "TED id": "tedUUID",   # 👈 este era el fallo
}

In [84]:
import pandas as pd
from pathlib import Path

# 1) Cargar el unificado antiguo
old_path = Path("/home/jarenas/Datasets/PLACE/2025/insiders_unificado.parquet")
df_unif = pd.read_parquet(old_path, engine="fastparquet")

# por si acaso hubiera columnas duplicadas
df_unif = df_unif.loc[:, ~df_unif.columns.duplicated()]

# 2) Elegir 5 ids aleatorios del nuevo dataframe
sample_ids = df_latest["id"].dropna().sample(5, random_state=42).tolist()

# 3) Subconjuntos
df_latest_5 = df_latest[df_latest["id"].isin(sample_ids)].copy()

cols_compare_old = [
    "id",
    "updated",
    "objective",   # ~ title
    "summary",
    "link",
    "ContractFolderStatus_ContractFolderStatusCode",  # estado
    "expedient",   # expediente
    "ContractFolderStatus_ProcurementProject_Name",  # objeto
    "budget",
    "ContractFolderStatus_ProcurementProject_BudgetAmount_TaxExclusiveAmount",
    "ContractFolderStatus_ProcurementProject_BudgetAmount_TotalAmount",
    "ContractFolderStatus_ProcurementProject_PlannedPeriod_DurationMeasure",
    "cpv",
    "url.administrativo",
    "url.id_administrativo",
    "url.tecnico",
    "url.id_tecnico",
    "tedUUID",
]

cols_compare_old = [c for c in cols_compare_old if c in df_unif.columns]

df_unif_5 = df_unif[df_unif["id"].isin(sample_ids)][cols_compare_old].copy()

# 4) Mostrar lado a lado (ordenados por id para facilitar comparación)
display(df_latest_5.sort_values("id"))
display(df_unif_5.sort_values("id"))

print("IDs comparados:")
for i in sample_ids:
    print(i)

,id,updated,title,summary,link,estado,expediente,objeto,valor_estimado,presupuesto_sin_iva,presupuesto_con_iva,duracion_dias,cpv_list,pliego_tecnico_URI,pliego_tecnico_filename,pliego_admin_URI,pliego_admin_filename,TED id
91662,https://contrataciondelestado.es/sindicacion/l...,2025-09-15T07:50:17.922+02:00,"Suministro, en función de las necesidades, de ...",Id licitación: CON-4115; Órgano de Contratació...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,CON-4115,"Suministro, en función de las necesidades, de ...",22560.00,11280.00,13648.80,365.0,"[39298700, 18530000, 18512200]",https://contrataciondelestado.es/wps/wcm/conne...,PCAP_suministro_trofeos_deportes_corregido_PBL...,https://contrataciondelestado.es/wps/wcm/conne...,PPT_trofeos_iva corregido.pdf,None
15619,https://contrataciondelestado.es/sindicacion/l...,2025-02-11T15:20:13.711+01:00,Renovación de las capacidades computacionales ...,Id licitación: Renovación capacidades; Órgano ...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,Renovación capacidades,Renovación de las capacidades computacionales ...,18181.00,18181.00,21999.98,30.0,[30200000],https://contrataciondelestado.es/FileSystem/se...,report_ogando_DI_SDA_24-2022_10.pdf,None,None,None
102264,https://contrataciondelestado.es/sindicacion/l...,2025-10-06T10:15:56.722+02:00,Explotación del servicio de la cafetería ubica...,Id licitación: E-CON-2025-38/CS/AM; Órgano de ...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,E-CON-2025-38/CS/AM,Explotación del servicio de la cafetería ubica...,283500.00,0.00,0.00,1460.0,[55330000],https://contrataciondelestado.es/FileSystem/se...,PCA-2025-39.pdf,https://contrataciondelestado.es/FileSystem/se...,PPT-2025-33.pdf,None
173556,https://contrataciondelestado.es/sindicacion/l...,2025-06-30T14:31:28.646+02:00,Contrato derivado del Acuerdo Marco para alqui...,Id licitación: TSA0076623-134; Órgano de Contr...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,TSA0076623-134,Contrato derivado del Acuerdo Marco para alqui...,31152.00,31152.00,37693.92,249.0,[45500000],https://contrataciondelestado.es/FileSystem/se...,TSA0076623 PCAP ALQ MAQUINARIA CORDOBA PRTR.pdf,https://contrataciondelestado.es/FileSystem/se...,TSA0076623 PPT ALQ MAQUINARIA CORDOBA PRTR.pdf,None
96121,https://contrataciondelestado.es/sindicacion/l...,2025-11-25T12:14:05.593+01:00,Obra de automatización y telecontrol de las co...,Id licitación: O6S-170/2025; Órgano de Contrat...,https://contrataciondelestado.es/wps/poc?uri=d...,EV,O6S-170/2025,Obra de automatización y telecontrol de las co...,206611.37,206611.37,249999.76,90.0,[45232151],https://contrataciondelestado.es/FileSystem/se...,PLIEGO ADMINISTRATIVO O6S-170-2025.pdf,https://contrataciondelestado.es/FileSystem/se...,Proyecto Diputacion Sindicato Aguas Dolores.pdf,None

,id,updated,objective,summary,link,ContractFolderStatus_ContractFolderStatusCode,expedient,ContractFolderStatus_ProcurementProject_Name,budget,ContractFolderStatus_ProcurementProject_BudgetAmount_TaxExclusiveAmount,ContractFolderStatus_ProcurementProject_BudgetAmount_TotalAmount,ContractFolderStatus_ProcurementProject_PlannedPeriod_DurationMeasure,cpv,url.administrativo,url.id_administrativo,url.tecnico,url.id_tecnico,tedUUID
id_internal,,,,,,,,,,,,,,,,,,
1ecf900c45d25ca9caf252dc65441d1a,https://contrataciondelestado.es/sindicacion/l...,2025-09-15 05:50:17.922000+00:00,"Suministro, en función de las necesidades, de ...",Id licitación: CON-4115; Órgano de Contratació...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,CON-4115,"Suministro, en función de las necesidades, de ...",22560.00,11280.00,13648.80,1.0,18512200.0,https://contrataciondelestado.es/wps/wcm/conne...,370a8cfa3a796aaf2ae0663bb512ab74,https://contrataciondelestado.es/wps/wcm/conne...,68bea099ad8f01efa85000fff33c48d9,None
6b24fac092391e86ff7c61b6faa930a2,https://contrataciondelestado.es/sindicacion/l...,2025-02-11 14:20:13.711000+00:00,Renovación de las capacidades computacionales ...,Id licitación: Renovación capacidades; Órgano ...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,Renovación capacidades,Renovación de las capacidades computacionales ...,18181.00,18181.00,21999.98,30.0,30200000.0,https://contrataciondelestado.es/FileSystem/se...,a1932db0ab54cf8214898b3040620174,None,None,None
f1d70ccfdf4a571de304d4c3a0326292,https://contrataciondelestado.es/sindicacion/l...,2025-10-06 08:15:56.722000+00:00,Explotación del servicio de la cafetería ubica...,Id licitación: E-CON-2025-38/CS/AM; Órgano de ...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,E-CON-2025-38/CS/AM,Explotación del servicio de la cafetería ubica...,283500.00,0.00,0.00,4.0,55330000.0,https://contrataciondelestado.es/FileSystem/se...,1c2ff4eed690efb3709b2c4382182135,https://contrataciondelestado.es/FileSystem/se...,314a851ba3b4e7816dfef55029818ba2,None
dfc064f98cda3387a19f2aab858615fe,https://contrataciondelestado.es/sindicacion/l...,2025-06-30 12:31:28.646000+00:00,Contrato derivado del Acuerdo Marco para alqui...,Id licitación: TSA0076623-134; Órgano de Contr...,https://contrataciondelestado.es/wps/poc?uri=d...,RES,TSA0076623-134,Contrato derivado del Acuerdo Marco para alqui...,31152.00,31152.00,37693.92,NaN,45500000.0,https://contrataciondelestado.es/FileSystem/se...,298ee079967d7774c0144db2bc0a0556,https://contrataciondelestado.es/FileSystem/se...,8be71a4556e93b964bf7722acb370c98,None
a37898e3cbbb5209981cb398a95348c5,https://contrataciondelestado.es/sindicacion/l...,2025-11-25 11:14:05.593000+00:00,Obra de automatización y telecontrol de las co...,Id licitación: O6S-170/2025; Órgano de Contrat...,https://contrataciondelestado.es/wps/poc?uri=d...,EV,O6S-170/2025,Obra de automatización y telecontrol de las co...,206611.37,206611.37,249999.76,3.0,45232151.0,https://contrataciondelestado.es/FileSystem/se...,4b24939fb9aa2767d27a243b337126bf,https://contrataciondelestado.es/FileSystem/se...,e0af899dbf96dc9df46d4159e77828fd,None

IDs comparados:
https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/14385184
https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/18013055
https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/17572443
https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/16658649
https://contrataciondelestado.es/sindicacion/licitacionesPerfilContratante/17518351

In [79]:
df_latest.columns

Index(['id', 'updated', 'title', 'summary', 'link', 'estado', 'expediente',
       'objeto', 'valor_estimado', 'presupuesto_sin_iva',
       'presupuesto_con_iva', 'duracion_dias', 'cpv_list',
       'pliego_tecnico_URI', 'pliego_tecnico_filename', 'pliego_admin_URI',
       'pliego_admin_filename', 'TED id'],
      dtype='object')

In [80]:
df_old.columns

Index(['id', 'link', 'summary', 'objective', 'updated', 'expedient',
       'ContractFolderStatus_ContractFolderStatusCode',
       'ContractFolderStatus_LocatedContractingParty_ContractingPartyTypeCode',
       'ContractFolderStatus_LocatedContractingParty_ActivityCode',
       'ContractFolderStatus_LocatedContractingParty_BuyerProfileURIID',
       ...
       'ContractFolderStatus_LocatedContractingParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_ParentLocatedParty_PartyName_Name',
       'ContractFolderStatus_TenderingProcess_ParticipationRequestReceptionPeriod_Description',
       'ContractFolderStatus_TenderResult_SubcontractTerms_Rate',
       'ContractFolderStatus_TenderResult_SubcontractTerms_Description',
       'ContractFolderStatus_ProcurementProjectLot_TenderingTerms_AwardingTerms_AwardingCriteria_ID',
       'deleted_on', 'url.administrativo', 'url.id_administrativo',
       'url.id_tecnico', 'url.tecnico'],
      dtype='object', length=214)